! 08_pajara[8]-symmetric.scl
!
 TOP pajara (symmetric form).
 8
!
 106.6
 385.3
 491.9
 598.5
 705.0
 983.8
 1090.3
 1196.9
!
! Two 4:5:6:7 chords.
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_18544.html#18550
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_17047-19547.json
! topic_id = 18544
! msg_id = 18550
