! 08_wauchope_symmetrical.scl
!
 Two 10:12:15:18 chords rooted a 7:5 apart.
 8
!
 21/20
 7/6
 5/4
 7/5
 3/2
 5/3
 7/4
 2/1
!
! Ken Wauchope's "symmetrical scale in just intonation".
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_18544.html#18550
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_17047-19547.json
! topic_id = 18544
! msg_id = 18550
