! 12_class.scl
!
 31 dyads covered by 4 tetrads (7-limit).
 12
!
 21/20
 35/32
 6/5
 5/4
 21/16
 7/5
 3/2
 25/16
 42/25
 7/4
 15/8
 2/1
!
! Erv Wilson, 1969.
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_11205.html#11235
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_9945-12429.json
! topic_id = 11205
! msg_id = 11235
