! 12_o8x[13].scl
!
 Two harmonic series segments (cap 16) rooted a 3:2 apart.
 12
!
 13/12
 9/8
 7/6
 5/4
 4/3
 11/8
 3/2
 13/8
 5/3
 7/4
 15/8
 2/1
!
! Carl Lumma, after David Canright.
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_20009.html#20030
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_19548-22047.json
! topic_id = 20009
! msg_id = 20030
