! E:\Cakewalk\scales\12to30subharm12.scl
!
subharmonic 12 to 30 in 15
 15
!
 30/29
 15/14
 10/9
 15/13
 6/5
 5/4
 30/23
 15/11
 10/7
 3/2
 30/19
 5/3
 30/17
 15/8
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_25104.html#25104
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_22048-29396.json
! topic_id = 25104
! msg_id = 25104
