! 26EDO-IbnSina.scl
!
Tempering of Ibn Sina's 1/1-14/13-7/6-4/3-3/2-21/13-7/4-2/1
 7
!
 138.46154
 276.92308
 507.69231
 692.30769
 830.76923
 969.23077
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_16005.html#16005
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_12292-17046.json
! topic_id = 16005
! msg_id = 16005
