! E:\9tonegoldsilvercombined.scl
!
9 note gold silver combined may 8th 2009
 9
!
 118.86332
 235.77738
 366.91254
 510.73163
 599.99564
 718.86136
 13/8
 1076.29807
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_83517.html#83517
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_81621-85537.json
! topic_id = 83517
! msg_id = 83517
