! abacbadabc-marvtrans.scl
!
Transversal of marvel tempering of 7-limit scale with mean variety four
 10
!
 16/15
 256/225
 4096/3375
 4/3
 64/45
 1024/675
 8/5
 128/75
 2048/1125
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_19601.html#19608
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_18428-20927.json
! topic_id = 19601
! msg_id = 19608
