! arab_segah-99edo.scl
!
99-edo Arab Segah with extra slightly raised leading tone to final
  8
!
  145.45455
  351.51515
  557.57576
  703.03030
  848.48485
  1054.54545
  1066.66667
  2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_105716.html#105719
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 105716
! msg_id = 105719
