! arch_enh_cheese.scl
!
Archytas' enharmonic with just 5/4's 'round a circle of 5-ET
 15
!
 44.916
 93.686
 240.000
 284.916
 333.686
 480.000
 524.916
 573.686
 720.000
 764.916
 813.686
 960.000
 1004.916
 1053.686
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_6827.html#6856
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_5960-7013.json
! topic_id = 6827
! msg_id = 6856
