! balasept-under.scl
!
5.7.13.15.21 tuning based on a single Balasept sequence
  12
!
  21/20
  277/240
  97/80
  13/10
  4/3
  7/5
  3/2
  97/60
  26/15
  28/15
39/20
  2/1
! Balasept -c recurrent sequence, x^15 = 4x + 4
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_95448.html#95642
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 95448
! msg_id = 95642
