! bala_semifo.scl
!
Burkinabe typical semifourth pentatonic bala feast scale
  12
!
  135/104
  26/23
  104/69
  207/160
  13/10
  45/26
  104/69
  2/1
  69/40
  26/15
  52/23
  2/1
! harmonic temperament out of primes 3, 5, 13, 23, Dudon 1987
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_95448.html#95459
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 95448
! msg_id = 95459
