! beardsley.scl
!
David Beardsley's scale used in "Science Friction". superparticular
 12
!
 17/16
 9/8
 19/16
 5/4
 21/16
 11/8
 3/2
 13/8
 27/16
 7/4
 15/8
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_3510.html#3510
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_2468-5959.json
! topic_id = 3510
! msg_id = 3510
