!Billter4_as3more_favourable.scl
!
Ab -1 Eb -1 Bb 0 F -3.5 C -4 G -4 D -4 A -4.5 E 0 B 0 F# 0 C# -2 G#
12
!
97.5
196
298.5
391.5
501.5
595.5
700
797.5
894
999.5
1093.5
2/1
!
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_77204.html#77445
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_76217-79116.json
! topic_id = 77204
! msg_id = 77445
