! buzurg_al-erin10.scl
!
Decatonic with septimal Buzurg, Rastlike modes (cf. Secor, blarney.txt)
  10
!
  14/13
  8/7
  16/13
  4/3
  56/39
  3/2
  21/13
  12/7
  24/13
  2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_105598.html#105598
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 105598
! msg_id = 105598
