! catakleismic34semitransversal.scl
!
17 note 2.3.7 semitransversal of Catakleismic[34]
 17
!
 28/27
 243/224
 9/8
 7/6
 243/196
 9/7
 4/3
 112/81
 81/56
 3/2
 14/9
 392/243
 12/7
 16/9
 448/243
 27/14
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_19423.html#19423
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_18428-20927.json
! topic_id = 19423
! msg_id = 19423
