! cons21.scl
!
 Set of intervals with num + den <= 21 not exceeding 2/1
 24
!
 11/10
 10/9
 9/8
 8/7
 7/6
 6/5
 11/9
 5/4
 9/7
 4/3
 11/8
 7/5
 10/7
 3/2
 11/7
 8/5
 13/8
 5/3
 12/7
 7/4
 9/5
 11/6
 13/7
 2/1
!
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_66272.html#66314
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_55190-71650.json
! topic_id = 66272
! msg_id = 66314
