! c:\win98\desktop\cupid.scl
!
 Decatonic MOS from 13-tET.
 10
!
 184.615 !......2
 276.923 !......3
 369.231 !......4
 553.846 !......6
 646.154 !......7
 738.462 !......8
 923.077 !.....10
 1015.385 !....11
 1107.692 !....12
 1200.000 !....13
!
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_7127.html#7127
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_0-19436.json
! topic_id = 7127
! msg_id = 7127
