! cw19_5.scl
!
CalkinWilf(<19 30 44|)
 19
!
 135/128
 27/25
 9/8
 75/64
 6/5
 5/4
 32/25
 4/3
 25/18
 36/25
 3/2
 25/16
 8/5
 5/3
 128/75
 9/5
 15/8
 48/25
 2/1
! cw19_7.scl
!
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_21119.html#21119
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_20928-21395.json
! topic_id = 21119
! msg_id = 21119
