! cw19_11.scl
!
CalkinWilf(<19 30 44 53 66|)
 19
!
 35/33
 12/11
 9/8
 7/6
 6/5
 5/4
 9/7
 4/3
 7/5
 10/7
 3/2
 14/9
 8/5
 5/3
 7/4
 9/5
 11/6
 40/21
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_21119.html#21119
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_20928-21395.json
! topic_id = 21119
! msg_id = 21119
