! decab.scl
! [21/20, 16/15, 15/14, 10/9, 21/20, 15/14, 16/15, 21/20, 10/9, 15/14]
(10/9) <=> (16/15) transform of decaa
10
!
21/20
28/25
6/5
4/3
7/5
3/2
8/5
42/25
28/15
2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_4563.html#4563
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_2440-7444.json
! topic_id = 4563
! msg_id = 4563
