! Dent-YN-RWT.scl
!
Tom Dent's Young-Neidhardt well-temperament (rationalized by G. Secor)
12
!
560/531
2643/2360
70/59
74/59
315/236
1329/944
883/590
280/177
890/531
105/59
887/472
2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_75816.html#75910
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_71651-76216.json
! topic_id = 75816
! msg_id = 75910
