! diamond9plus.scl
9-limit tonality diamond extended with two secors
21
!
115.587
10/9
9/8
8/7
7/6
6/5
5/4
9/7
4/3
7/5
10/7
3/2
14/9
8/5
5/3
12/7
7/4
16/9
9/5
1084.413
2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_92097.html#92097
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 92097
! msg_id = 92097
