! didymus9.scl
!
A distributionally even scale in didymus (81/80 planar) temperament, aabacabac
 9
!
 192.70000
 385.40000
 461.68000
 654.38000
 697.04000
 889.74000
 966.02000
 1158.72000
 1201.38000
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_19356.html#19356
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_18428-20927.json
! topic_id = 19356
! msg_id = 19356
