! E:\DimensionECF.scl
!
Dimension ECF (Dimension Tuning Optimized for Fifths)
11
!
119.55822
28/25
6/5
613/500
505.77499
621.75868
3/2
201/125
837/500
1011.52634
1831/1000
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_96543.html#96543
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 96543
! msg_id = 96543
