! E:\dimensionsquared.scl
!
dimension squared
 12
!
 28/25
 117/100
 6/5
 613/500
 505.77499
 3/2
 1573/1000
 817.46922
 892.06285
 1011.52634
 1831/1000
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_42.html#24378
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_22048-29396.json
! topic_id = 42
! msg_id = 24378
