! eb24-moha-bayyati-septimal_Eb.scl
!
Lower Mohajira tetrachord with 21/16; upper Bayyati ~12:13:14:16
  7
!
  132.24835
  341.46217
  473.71052
  704.60690
  836.85526
  969.10361
  2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_89383.html#89452
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_88077-89999.json
! topic_id = 89383
! msg_id = 89452
