! evangelina.scl
!
 Erv Wilson's everyday go-to scale (Kraig Grady, T66325).
 22
!
 135/128
 13/12
 10/9
 9/8
 7/6
 11/9
 5/4
 81/64
 4/3
 11/8
 45/32
 17/12
 3/2
 405/256
 13/8
 5/3
 27/16
 7/4
 11/6
 15/8
 243/128
 2
!
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_66272.html#66326
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_55190-71650.json
! topic_id = 66272
! msg_id = 66326
