! gizmo14-ji_transversal.scl
!
Possible JI transversal of gizmo14.scl or gizmo14-pote.scl
  14
!
  91/88
  9/8
  11/9
  14/11
  21/16
  11/8
  3/2
  14/9
  13/8
  22/13
  7/4
  11/6
  63/32
  2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_105298.html#105298
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 105298
! msg_id = 105298
