! grady_14.scl
!
 Kraig Grady, letter to Lou Harrison, published in 1/1 7 (1) 1991 p5.
 14
!
 21/20
 9/8
 7/6
 5/4
 21/16
 4/3
 7/5
 3/2
 63/40
 27/16
 7/4
 15/8
 63/32
 2/1
!
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_76310.html#76311
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_76217-79116.json
! topic_id = 76310
! msg_id = 76311
