!Groenewald_simplified_Bach.scl
!
Journal: Ars Organi Volume#57, Issue 1, March(2009) p.39
!
12
!
90.225 ! C#
189.25 ! D
294.135 ! Eb
386.606 ! E
498.045 ! F
588.270 ! F#
693.175 ! G
792.180 ! G#
887.275 ! A
996.090 ! Bb
1086.808 ! B
2/1
!
!
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_79337.html#83386
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_81621-85537.json
! topic_id = 79337
! msg_id = 83386
