! harcb12.scl
!
Scale of 16 harmonics from C and 16 subharmonics from B
! November 2005 - Petr Parizek
 12
!
 15/14
 9/8
 15/13
 5/4
 15/11
 11/8
 3/2
 13/8
 5/3
 7/4
 15/8
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_62541.html#62541
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_55190-71650.json
! topic_id = 62541
! msg_id = 62541
