!Horowitz.scl 
Leonard G.Horowitz's DMD,MA,MPH,DNM(hon.) scale completed by Sparschuh
!
12
!
2227/2112
9/8
313/264
5/4
4/3
45/32
3/2
835/528
37/22
313/176
15/8
2/1
!
![eof]
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_91766.html#91774
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 91766
! msg_id = 91774
