! iran_diat.scl
!
Iranian Diatonic from Dariush Anooshfar, Safi-a-ddin Armavi's scale from 125 ET
 7
!
 220.800 cents
 441.600 cents
 489.600 cents
 710.400 cents
 931.200 cents
 979.200 cents
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_77364.html#77873
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_76217-79116.json
! topic_id = 77364
! msg_id = 77873
