! jiri24a.scl
!
Just/rational intonation system -- with circulating 24-note set 
24
!
 36/35
 18/17
 12/11
 9/8
 15/13
 19/16
 11/9
 29/23
 13/10
 4/3
 11/8
 17/12
 16/11
 3/2
 20/13
 46/29
 18/11
 32/19
 26/15
 16/9
 11/6
 17/9
 35/18
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_18180.html#18180
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_0-19436.json
! topic_id = 18180
! msg_id = 18180
