! E:\Cakewalk\scales\john20110212.scl
!
john 2011 02 12 best
 20
!
 9/8
 8/7
 7/6
 6/5
 5/4
 9/7
 4/3
 11/8
 7/5
 10/7
 3/2
 11/7
 8/5
 5/3
 12/7
 7/4
 9/5
 11/6
 13/7
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_87588.html#96248
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 87588
! msg_id = 96248
