! jot17a.scl
!
Just octachord tuning -- 4:3-9:8-4:3 division, 17 steps (7 + 3 + 7), Bb-Bb
 17
!
 28/27
 14/13
 44/39
 7/6
 28/23
 28/22
 4/3
 112/81
 56/39
 3/2
 14/9
 21/13
 22/13
 7/4
 42/23
 21/11
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_6632.html#6688
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_5960-7013.json
! topic_id = 6632
! msg_id = 6688
