! kirnberger2.scl
!
Kirnberger 2: 1/2 synt. comma. "Die Kunst des reinen Satzes" (1774)
 12
!
 135/128
 9/8
 32/27
 5/4
 4/3
 45/32
 3/2
 405/256
 895.11186
 16/9
 15/8
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_43792.html#43830
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_40000-49986.json
! topic_id = 43792
! msg_id = 43830
