! kirnberger1.scl
!
Kirnberger's temperament 1 (1766)                                               
 12
!
 256/243
 9/8
 32/27
 5/4
 4/3
 45/32
 3/2
 128/81
 895.11200
 16/9
 15/8
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_4727.html#4734
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_2440-7444.json
! topic_id = 4727
! msg_id = 4734
