! lumma_wauchope-major.scl
!
 Two 8:10:12:15 chords rooted a 7:5 apart.
 8
!
 21/20
 5/4
 21/16
 7/5
 3/2
 7/4
 15/8
 2/1
!
! Carl Lumma, after Ken Wauchope, 1999.
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_18544.html#18550
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_17047-19547.json
! topic_id = 18544
! msg_id = 18550
