! mandelbaum7.scl
!
Mandelbaum's 7-limit 19-tone scale                                              
 19
!
 25/24
 15/14
 9/8
 7/6
 6/5
 5/4
 9/7
 4/3
 7/5
 36/25
 3/2
 14/9
 8/5
 5/3
 7/4
 9/5
 15/8
 27/14
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_104052.html#104052
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 104052
! msg_id = 104052
