! mandelbaum7keemun.scl
!
Keemun Fokkerization of mandelbaum7
! 
 19
! meantone: -8 to 10; magic: -6 to 12; keemun: -6 to 12
 25/24
 15/14
 9/8
 7/6
 6/5
 5/4
 9/7
 4/3
 7/5
 36/25
 3/2
 25/16
 8/5
 5/3
 7/4
 9/5
 15/8
 48/25
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_104052.html#104052
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 104052
! msg_id = 104052
