! marpurg2.scl
!
Marpurg 2. Neue Methode (1790)                                                  
 12
!
 109.775 cents
 9/8
 313.685 cents
 81/64
 4/3
 607.820 cents
 3/2
 811.730 cents
 27/16
 1015.640 cents
 1105.865 cents
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_4727.html#4727
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_2440-7444.json
! topic_id = 4727
! msg_id = 4727
