! mavsynch7.scl
Mavilla[7] in synch (brat=-1) tuning
! fifth satisfies f^4 + f^3 - 8 = 0
7
!
152.674307
370.988539
523.662846
676.337154
829.011461
1047.325693
1200.000000
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_12859.html#12859
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_12430-15927.json
! topic_id = 12859
! msg_id = 12859
