! MEANTONE-KILLER.scl
!
15 circulating notes of porcupine (/ sort of nusecond in the far keys)
15
!
67.
161.
228.
319.
390.
477.
552.
635.
714.
793.
876.
951.
1038.
1109.
1200.
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_102293.html#102297
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 102293
! msg_id = 102297
