! meandia.scl
Detempered Meantone[21]; contains 7-limit diamond
21
!
21/20
15/14
9/8
8/7
7/6
6/5
5/4
9/7
4/3
7/5
10/7
3/2
14/9
8/5
5/3
12/7
7/4
9/5
15/8
27/14
2
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_15660.html#15660
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_12430-15927.json
! topic_id = 15660
! msg_id = 15660
