! met24-ptolemy_hom_Bup.scl
!
Tempering of Ptolemy's Homalon or Equable Diatonic
  7
!
  150.00000
  312.89063
  495.70313
  703.12500
  853.12500
  1016.01563
  2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_105598.html#105598
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 105598
! msg_id = 105598
