! mmmgeo1.scl
!
Scale for MakeMicroMusic in Peppermint 24, maybe a bit like Georgian tunings
 7
!
 187.34894
 336.86046
 495.90439
 704.09561
 832.76485
 991.80879
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_3617.html#3619
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_2468-5959.json
! topic_id = 3617
! msg_id = 3619
