! mmmgeo4b.scl
!
Peppermint 24 scale for MakeMicroMusic, maybe a bit "Georgian-like"?  
 7
!
 208.19121
 367.23515
 495.90439
 704.09561
 863.13954
 1071.33075
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_3617.html#3619
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_2468-5959.json
! topic_id = 3617
! msg_id = 3619
