! mohaj-bala_213.scl
!
Parizekmic Mohajira+Bala scale, based on a double Bala sequence
  12
!
  16/15
  52/45
  71/60
  13/10
  4/3
  64/45
  3/2
  8/5
  26/15
  16/9
  39/20
  2/1
! Interleaved Bala -c recurrent sequences, x^8 - 2 = x
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_95448.html#95687
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 95448
! msg_id = 95687
