! C:\Program Files (x86)\Scala22\mostly-elevens-scale.scl
!
Scale derived mostly from elevens.
 17
!
 33/32
 12/11
 25/22
 33/28
 11/9
 14/11
 4/3
 7/5
 16/11
 3/2
 11/7
 18/11
 56/33
 16/9
 11/6
 21/11
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_28151.html#28151
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_22048-29396.json
! topic_id = 28151
! msg_id = 28151
