! notchedcube.scl
Otonal tetrads sharing a note with the root tetrad, a notched chord cube
28
!
49/48
25/24
21/20
15/14
35/32
9/8
8/7
7/6
6/5
49/40
5/4
9/7
21/16
4/3
7/5
10/7
35/24
3/2
49/32
25/16
8/5
5/3
12/7
7/4
25/14
9/5
15/8
2
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_64910.html#64910
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_55190-71650.json
! topic_id = 64910
! msg_id = 64910
