! O3-quasi-meso-iph7_C#.scl
!
Disjunct tetrachords ~1/1-56/51-26/21-4/3 a bit like Dudon's meso-iph7.scl
  7
!
  161.71875
  369.14062
  495.70313
  704.29687
  866.01563
  1073.43750
  2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_91501.html#93177
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 91501
! msg_id = 93177
