! O3-rast_moha_Cup.scl
!
Mode of Rast + Mohajira (Dudon) with near-pure 59/48 and 12:11 steps
  7
!
  207.42188
  357.42187
  495.70312
  703.12500
  854.29687
  1061.71875
  2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_91501.html#93138
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 91501
! msg_id = 93138
