! org1373a.scl
!
English organ tuning (1373) with 18:17:16 accidental semitones (Eb-G#)      
 12
!
 18/17
 9/8
 81/68
 81/64
 4/3
 24/17
 3/2
 27/17
 27/16
 243/136
 243/128
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_34979.html#36356
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_34615-37192.json
! topic_id = 34979
! msg_id = 36356
