! orwellian9.scl
!
A distributionally even scale in orwellian temperament, ababababc
 9
!
 43.33000
 270.47000
 387.99000
 431.32000
 658.46000
 701.79000
 928.93000
 972.26000
 1199.40000
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_19356.html#19356
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_18428-20927.json
! topic_id = 19356
! msg_id = 19356
