! oz17.scl
80-et commas 13-limit detempering of a chain of 16 fifths
17
!
22/21
13/12
9/8
13/11
16/13
14/11
4/3
18/13
13/9
3/2
11/7
13/8
22/13
16/9
13/7
21/11
2
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_11787.html#11788
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_9945-12429.json
! topic_id = 11787
! msg_id = 11788
