!OzYarmanApprox.scl
Ozan Yarman's 79-MOS-159ET splendid-beating rat. approx. by Sparschuh
!compiled within precision accuracy of less than 1 Cent deviation
!
12
!
19/18
28/25
25/21
64/51
4/3
45/32
3/2
128/81
42/25
25/14
47/25
2/1
!
![eof]
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_88448.html#88520
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_88077-89999.json
! topic_id = 88448
! msg_id = 88520
