! parapyth12trans.scl
!
A JI transversal of parapyth17.scl for use in calculations. If you temper out 352/351 and 364/363 it becomes parapyth17.
 12
!
 28/27
 9/8
 7/6
 14/11
 21/16
 11/8
 3/2
 14/9
 22/13
 7/4
 21/11
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_105023.html#105142
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 105023
! msg_id = 105142
