! parapyth12-7.scl
!
2.3.7 transversal of parapyth12
! 3-distributional even SLSLSMLSLSLM
! <<1 -2 -6||: -6 to 5; <<1 10 13||: 0 to 11; <<2 8 7||: 0 to 10 even
 12
!
 28/27
 9/8
 7/6
 81/64
 21/16
 112/81
 3/2
 14/9
 27/16
 7/4
 243/128
 2/1
! parapyth17-7.scl
!
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_105023.html#105146
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 105023
! msg_id = 105146
