! pep_dudon_ibina_E.scl
!
Peppermint tempering of Dudon's Ibina: 72:78:88:96:108:117:128:144
  7
!
  138.20166
  346.39287
  495.90439
  704.09561
  842.29727
  991.80879
  2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_89383.html#89445
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_88077-89999.json
! topic_id = 89383
! msg_id = 89445
