! pepbuzrg.scl
!
Peppermint 24 version of Buzurg variant (cf. buzurg1.scl)             
 8
!
 128.66925
 357.70273
 495.90439
 624.57364
 704.09561
 853.60713
 1120.47803
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_3617.html#3635
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_2468-5959.json
! topic_id = 3617
! msg_id = 3635
