! portent11.scl
!
A distributionally even scale in portent temperament, abababababc
11
!
151.534
233.784
385.318
467.568
619.102
701.352
852.886
935.136
966.707
1118.241
1200.491
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_19390.html#19390
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_18428-20927.json
! topic_id = 19390
! msg_id = 19390
