! ProposedVariationOnSparschuh442wideFrench5th.scl
!
Proposed revision: step 9 (A) at 885/529, 890.9 cents -- Margo Schulter
 12
!
 558/529
 592/529
 628/529
 662/529
 706/529
 744/529
 792/529
 837/529
 885/529
 942/529
 992/529
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_77364.html#77852
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_76217-79116.json
! topic_id = 77364
! msg_id = 77852
