! ragaldor.scl
!
Raga-like medieval European Dorian mode with ~7/6 and ~7/4, tempered version
 7
!
 208.191213 cents
 7/6
 495.904393 cents
 704.095607 cents
 912.286820 cents
 970.966512 cents
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_42424.html#42424
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_40000-49986.json
! topic_id = 42424
! msg_id = 42424
