! rbuzurg-buzurg_hijaz_Cup.scl
!
Qutb al-Din al-Shirazi's Buzurg plus upper Hijaz (JI 12:11-7:6-22:21)
  8
!
  133.35066
  361.88496
  495.23562
  628.58628
  704.76438
  857.12058
  1123.82190
  2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_91528.html#91541
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 91528
! msg_id = 91541
