! C:\Scala22\reflections.scl
!
7-limit (slightly tempered) "reflections" scale
  12
!
  28/27
  9/8
  7/6
  383.74300
  4/3
  7/5
  3/2
  14/9
  5/3
  7/4
  1083.12800
  2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_78385.html#78385
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_76217-79116.json
! topic_id = 78385
! msg_id = 78385
