! rodpoole.scl
!
Rod Poole's 13-limit scale
! http://anaphoriasouth.blogspot.com/2009/10/scale-develops-rod-pooles-tuning.html
 17
!
 33/32
 13/12
 9/8
 7/6
 11/9
 14/11
 4/3
 11/8
 13/9
 3/2
 14/9
 44/27
 27/16
 7/4
 11/6
 21/11
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_97196.html#97200
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 97196
! msg_id = 97200
