! Secor5_23TX.scl
!
George Secor's synchronous 5/23-comma temperament extraordinaire
 12
!
 62/59
 66/59
 70/59
 591/472
 631/472
 331/236
 353/236
 745/472
 395/236
 631/354
 221/118
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_88708.html#88894
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_88077-89999.json
! topic_id = 88708
! msg_id = 88894
