! SecorVRWT-24e.scl
!
George Secor's 24-triad proportional-beating Victorian rational well-temperament (24e), based on Ellis #2
12
!
 581/550
 28/25
 653/550
 345/275
 367/275
 31/22
 412/275
 871/550
 461/275
 89/50
 47/25
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_84986.html#85138
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_81621-85537.json
! topic_id = 84986
! msg_id = 85138
