! Secor5_23STX.scl
!
George Secor's synchronous 5/23-comma temperament extraordinaire
 12
!
 62/59
 66/59
 559/472
 591/472
 315/236
 331/236
 353/236
 745/472
 395/236
 210/118
 221/118
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_75816.html#76100
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_71651-76216.json
! topic_id = 75816
! msg_id = 76100
