! Secor5_23TX.scl
!
George Secor's synchronous 5/23-comma temperament extraordinaire
 12
!
 62/59
 66/59
 70/59
 591/472
 315/236
 331/236
 353/236
 745/472
 395/236
 1051/590
 221/118
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_87190.html#87190
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_85538-88076.json
! topic_id = 87190
! msg_id = 87190
