! semisixths-8.scl
!
8-note MOS of Semisixths [7, 9, 13, -2, 1, 5] temperament, TOP tuning
  8
!
  131.09135
  262.18270
  443.16029
  574.25164
  705.34299
  886.32059
  1017.41193
  1198.38953
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_52534.html#52568
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_52482-55189.json
! topic_id = 52534
! msg_id = 52568
