! sentdia.scl
Consists of the tetrads of detempered Sensi[27] = sensidia.scl
21
!
21/20
15/14
10/9
8/7
7/6
6/5
5/4
9/7
4/3
7/5
10/7
3/2
14/9
8/5
5/3
12/7
7/4
9/5
28/15
40/21
2
! [[0, -2, -1], [0, -1, -2], [0, -1, 0], [0, -1, -1], [0, 0, -1], [-1,
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_15658.html#15658
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_12430-15927.json
! topic_id = 15658
! msg_id = 15658
