!septenarius440Hzmk2.scl
!
TD's septenarius @ middle c'=262Hz or a'=440Hz
!
12
!
278/262 ! C# 
294/262 ! D
312/262 ! Eb
330/262 ! E
350/262 ! F
371/262 ! F#
393/262 ! G
416/262 ! G#
440/262 ! A
468/262 ! Bb
495/262 ! B
2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_69724.html#71154
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_55190-71650.json
! topic_id = 69724
! msg_id = 71154
