!septenarius440Hz.scl
!
sparschuh's septenarius @ middle c'=263Hz or a'=440Hz
!
12
!
278/263 ! C#
294/263 ! D
312/263 ! Eb
330/263 ! E
351/263 ! F
351/263 ! F#
393/263 ! G
416/263 ! G#
440/263 ! A
468/263 ! Bb
495/263 ! B
2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_69724.html#71147
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_55190-71650.json
! topic_id = 69724
! msg_id = 71147
