! sheiman_michael-phi_section.scl
!
Michael Sheiman's Phi Section scale, from Tuning List
  9
!
  149.464
  235.774
  273.024
  366.910
  466.181
  560.566
  597.316
  683.627
  833.090
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_94256.html#94256
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 94256
! msg_id = 94256
