! sims.scl
!
Ezra Sims' 18-tone mode                                                         
 18
!
 25/24
 13/12
 9/8
 7/6
 29/24
 5/4
 21/16
 11/8
 23/16
 3/2
 25/16
 13/8
 27/16
 7/4
 29/16
 15/8
 31/16
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_22968.html#23089
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_22050-25104.json
! topic_id = 22968
! msg_id = 23089
