! slendro_pc.scl
!
"Blown fifth" modern slendro, von Hornbostel                                    
 5
!
 234.000 cents
 468.000 cents
 702.000 cents
 936.000 cents
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_89891.html#89891
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_88077-89999.json
! topic_id = 89891
! msg_id = 89891
