! smalldi19c.scl
!
Small diesic 19-note scale containing glumma
! 
19
49/48
21/20
15/14
35/32
6/5
49/40
5/4
9/7
21/16
10/7
35/24
3/2
49/32
5/3
12/7
7/4
9/5
35/18
2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_4541.html#4541
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_2440-7444.json
! topic_id = 4541
! msg_id = 4541
