! smalldi19b.scl
!
Small diesic 19-note block, <16/15, 126/125, 2401/2400> commas
! 
19
!
50/49
21/20
8/7
7/6
6/5
49/40
5/4
48/35
7/5
10/7
35/24
8/5
80/49
5/3
12/7
7/4
40/21
49/25
2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_4541.html#4541
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_2440-7444.json
! topic_id = 4541
! msg_id = 4541
