!Spa_s_s_7_lim.scl
Sparschuh's 7-limit ~JI cycle of a dozen tempered 5ths
12
!
21/20!C# ~ 084cents
9/8 ! D. ~ 204
7/6 ! Eb ~ 267
5/4 ! E. ~ 386
4/3 ! F. ~ 498
7/5 ! F# ~ 583
3/2 ! G. ~ 702
8/5 ! G# ~ 814
5/3 ! A. ~ 884
7/4 ! Bb ~ 969
15/8! B. ~1088 
2/1 ! C'
!
!
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_82079.html#82124
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_81621-85537.json
! topic_id = 82079
! msg_id = 82124
