! Sparschuh12.scl
!
Sparschuh's old piano @ c"=575Hz & a"=880Hz in 'Septenarian' style
12
!
37/35 !_! C#
196/175 ! D
208/175 ! D#
94/75 !_! E
234/175 ! F
148/105 ! F#
262/175 ! G
832/525 ! G#
176/105 ! A
312/175 ! A#
47/25 !_! B
2/1
!
!
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_81042.html#81840
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_81621-85537.json
! topic_id = 81042
! msg_id = 81840
