! stanhope.scl
!
Well temperament of Charles, third earl of Stanhope (1806)
 12
!
 256/243
 196.09000
 32/27
 8192/6561
 4/3
 1024/729
 3/2
 128/81
 890.22500
 16/9
 4096/2187
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_55055.html#55055
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_52482-55189.json
! topic_id = 55055
! msg_id = 55055
