!StanhopeMonochord.scl
Stanhope's (1806) monochord string lenghts compiled by A.Sparschuh
12
! 
120/113 ! C#
120/107 ! D
120/101 ! Eb
120/96  ! E
120/90  ! F 
120/85  ! F#
120/80  ! G
120/75  ! G#
120/71  ! A
120/67  ! Bb
120/64  ! B
2/1
!
![eof]
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_55055.html#87693
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_85538-88076.json
! topic_id = 55055
! msg_id = 87693
