! steldia.scl
Stellated hexany plus diamond; superparticular ratios
18
!
15/14
8/7
7/6
6/5
60/49
5/4
9/7
4/3
7/5
10/7
3/2
8/5
5/3
12/7
7/4
25/14
15/8
2
! [-1..0, -1..0, -1..1]
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_15662.html#15662
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_12430-15927.json
! topic_id = 15662
! msg_id = 15662
