! supermagic7.scl
!
A distributionally even scale in supermagic temperament, abababc
 7
!
 59.11000
 321.68000
 380.79000
 643.36000
 702.47000
 965.04000
 1201.03000
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_19356.html#19356
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_18428-20927.json
! topic_id = 19356
! msg_id = 19356
