! synslenstar.scl
Harmony optimal {49/48, 81/80, 126/125} Fokker block
19
!
21/20
16/15
10/9
7/6
6/5
5/4
35/27
4/3
7/5
35/24
3/2
14/9
8/5
5/3
7/4
16/9
28/15
35/18
2
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_12904.html#12904
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_12430-15927.json
! topic_id = 12904
! msg_id = 12904
