! tamil_vi.scl
!
Vilarippalai scale in Tamil music, Vidyasankar Sundaresan
 12
!
 256/243
 10/9
 32/27
 5/4
 4/3
 45/32
 40/27
 128/81
 5/3
 16/9
 15/8
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_11331.html#11335
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_9945-12429.json
! topic_id = 11331
! msg_id = 11335
