! tetratetra.scl
!
tetratetradic scale on 6:7:9:11! 22:27:33 on degree 11! spooky pentatonic!
 12
!
 77/72
 12/11
 9/8
 7/6
 14/11
 11/8
 3/2
 18/11
 121/72
 7/4
 11/6
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_55769.html#55778
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_55190-71650.json
! topic_id = 55769
! msg_id = 55778
