! trithagorean[13] -- tritave with 5_3 generator.scl
!
Tritave scale with a 5/3 generator.
 13
!
 27/25
 729/625
 19683/15625
 3125/2187
 125/81
 5/3
 9/5
 243/125
 6561/3125
 15625/6561
 625/243
 25/9
 3/1
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_28223.html#28223
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_22048-29396.json
! topic_id = 28223
! msg_id = 28223
