! uruk.scl
Jon Lyle Smith's "Uruk" scale
17
!
21/20
15/14
9/8
189/160
135/112
81/64
4/3
7/5
10/7
3/2
63/40
45/28
27/16
567/320
405/224
243/128
2/1
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_16210.html#16213
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_12292-17046.json
! topic_id = 16210
! msg_id = 16213
