! variant-on-marcel_12.scl
!
Expansion of Marcel de Velde's JI tuning, TL #90805 (9 July 2010)
  12
!
  28/27
  13/12
  7/6
  11/9
  4/3
  13/9
  3/2
  14/9
  13/8
  7/4
  11/6
  2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_90656.html#90819
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_90000-106393.json
! topic_id = 90656
! msg_id = 90819
