!Wegscheider_Bach_Snerha.scl
!
http://www.wegscheider-orgel.de/html/artikel.php?filename=artikel.php&tabname=Artikel&sz=0
12
!
92
192.8
296.2
388.4
500.1
590.1
697.3
794
890.6
998.2
1088.1
2/1
!
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_77204.html#77445
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_76217-79116.json
! topic_id = 77204
! msg_id = 77445
