! werckmeisterIV_variant.scl
!
Werckmeister IV with 1/3 syntonic comma temperings
 12
!
 85.00995
 196.74124
 32/27
 393.48248
 4/3
 45/32
 694.78624
 785.01123
 891.52748
 1003.25876
 15/8
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_73833.html#74132
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_71651-76216.json
! topic_id = 73833
! msg_id = 74132
