! werck3.scl
!
Andreas Werckmeister's temperament III (the most famous one, 1681)
  12
!
  256/243
  192.18000
  32/27
  390.22500
  4/3
  1024/729
  696.09000
  128/81
  888.26999
  16/9
  1092.18000
  2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_69073.html#69239
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_55190-71650.json
! topic_id = 69073
! msg_id = 69239
