! wilclav.scl
Erv Wilson's clavochord scale from Xenharmonikon 4
19
!
45/44
12/11
9/8
40/33
5/4
14/11
21/16
15/11
11/8
45/32
3/2
18/11
27/16
12/7
7/4
20/11
15/8
21/11
2
!
! https://yahootuninggroupsultimatebackup.github.io/tuning-math/topicId_11394.html#11396
!
! [info]
! source = Mailing lists
! file = tuning-math/messages/yahoo_tuning-math_messages_api_raw_9945-12429.json
! topic_id = 11394
! msg_id = 11396
