! zartehijaz1.scl
!
Scale from Zarlino temperament extraordinaire -- lower Hijaz tetrachord
 9
!
 120.94826
 433.51722
 504.18965
 625.13792
 708.37930
 925.13792
 1008.37930
 1129.32757
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/makemicromusic/topicId_9674.html#9674
!
! [info]
! source = Mailing lists
! file = makemicromusic/messages/yahoo_makemicromusic_messages_api_raw_7014-9791.json
! topic_id = 9674
! msg_id = 9674
