! zest24_Suz-i_Dilara_Gbup.scl
!
Zest-24 Suz-i Dilara near suggested values in Ozan Yarman's 79MOS
 7
!
 203.90624
 421.87500
 505.07812
 696.09374
 912.89062
 1129.68749
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_77885.html#77885
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_76217-79116.json
! topic_id = 77885
! msg_id = 77885
