! zest24_Suz-i_Dilara_Abup.scl
!
Zest-24 Suz-i Dilara similar to tuning in Ozan Yarman's 79MOS
 7
!
 217.96876
 421.87500
 492.18750
 708.98438
 925.78125
 1117.96875
 2/1
!
! https://yahootuninggroupsultimatebackup.github.io/tuning/topicId_77885.html#77885
!
! [info]
! source = Mailing lists
! file = tuning/messages/yahoo_tuning_messages_api_raw_76217-79116.json
! topic_id = 77885
! msg_id = 77885
