! levy-06-darbari.scl
!
Ex. 6: Nazakat & Salamat Ali Khan, Darbārī
 7
!
 202.0  ! Re
 338.0  ! Ga♭
 505.0  ! Ma
 700.0  ! Pa
 818.0  ! Dha♭
 1011.0 ! Ni♭
 1200.0
!
! [info]
! source = contrib
! reference = Levy, Mark. 1982. Intonation in North Indian Music. Biblia Impex
! ref_url = https://archive.org/details/intonationinnort0000mark
! country = Pakistan
! contributor = naren
! contrib_date = 2026-06-06
