! Angola_Chisende_10450.scl
!
Chisende 10450 (Likembe), Angola
 6
!
 183.0
 371.0
 531.0
 696.0
 860.0
 1187.0
!
! Kubik, Gerhard (1980). Likembe tunings of Kufuna Kandonga (Angola).
! African Music: Journal of the International Library of African Music,
! 6(1):70-88.
!
! [info]
! source = DaMuSc
! measured_id = M0195
! ref_id = 15
! country = Angola
! doi = https://doi.org/10.21504/amj.v6i1.1097
