! Angola_Chisende_10618.scl
!
Chisende 10618 (Likembe), Angola
 6
!
 149.0
 361.0
 538.0
 674.0
 851.0
 1200.0
!
! Kubik, Gerhard (1980). Likembe tunings of Kufuna Kandonga (Angola).
! African Music: Journal of the International Library of African Music,
! 6(1):70-88.
!
! [info]
! source = DaMuSc
! measured_id = M0196
! ref_id = 15
! country = Angola
! doi = https://doi.org/10.21504/amj.v6i1.1097
