! Bolivia_Sikura_1.scl
!
Measured scale M0150 in DaMuSc
 16
!
 225.0
 400.0
 540.0
 730.0
 940.0
 1030.0
 1230.0
 1390.0
 1620.0
 1710.0
 1900.0
 2100.0
 2220.0
 2410.0
 2610.0
 2710.0
!
! M. Kuss. Music in Latin America and the Caribbean: An Encyclopedic
! History: Volume 1: Performing Beliefs: Indigenous Peoples of South
! America, Central America, and Mexico. University of Texas Press, 2010
!
! [info]
! source = DaMuSc
! measured_id = M0150
! ref_id = 33
