! Bolivia_Sikura_2.scl
!
Measured scale M0151 in DaMuSc
 16
!
 200.0
 390.0
 520.0
 710.0
 910.0
 1010.0
 1200.0
 1390.0
 1590.0
 1710.0
 1900.0
 2090.0
 2200.0
 2390.0
 2590.0
 2690.0
!
! M. Kuss. Music in Latin America and the Caribbean: An Encyclopedic
! History: Volume 1: Performing Beliefs: Indigenous Peoples of South
! America, Central America, and Mexico. University of Texas Press, 2010
!
! [info]
! source = DaMuSc
! measured_id = M0151
! ref_id = 33
