! China_83.scl
!
Measured scale M0141 in DaMuSc
 16
!
 154.0
 343.0
 497.0
 697.0
 908.0
 1042.0
 1145.0
 1238.0
 1398.0
 1568.0
 1729.0
 1935.0
 2124.0
 2289.0
 2350.0
 2479.0
!
! R. Yu-An, E. C. Carterette, and W. Yu-Kui. A comparison of the musical
! scales of the ancient chinese bronze bell ensemble and the modern
! bamboo flute. Percept. Psychophys., 41(6):547-562, 1987. doi:
! 10.3758/BF03210489
!
! [info]
! source = DaMuSc
! measured_id = M0141
! ref_id = 23
