! China_84.scl
!
Measured scale M0142 in DaMuSc
 12
!
 158.0
 338.0
 695.0
 896.0
 1142.0
 1235.0
 1399.0
 1564.0
 1926.0
 2118.0
 2277.0
 2458.0
!
! R. Yu-An, E. C. Carterette, and W. Yu-Kui. A comparison of the musical
! scales of the ancient chinese bronze bell ensemble and the modern
! bamboo flute. Percept. Psychophys., 41(6):547-562, 1987. doi:
! 10.3758/BF03210489
!
! [info]
! source = DaMuSc
! measured_id = M0142
! ref_id = 23
