! China_85.scl
!
Measured scale M0143 in DaMuSc
 12
!
 149.0
 339.0
 692.0
 884.0
 1099.0
 1186.0
 1334.0
 1551.0
 1853.0
 2047.0
 2195.0
 2678.0
!
! R. Yu-An, E. C. Carterette, and W. Yu-Kui. A comparison of the musical
! scales of the ancient chinese bronze bell ensemble and the modern
! bamboo flute. Percept. Psychophys., 41(6):547-562, 1987. doi:
! 10.3758/BF03210489
!
! [info]
! source = DaMuSc
! measured_id = M0143
! ref_id = 23
