! Colombia_Marimba_06.scl
!
Marimba 6 (Marimba), Colombia
 17
!
 100.0
 210.0
 280.0
 470.0
 670.0
 860.0
 1000.0
 1160.0
 1340.0
 1490.0
 1640.0
 1840.0
 1990.0
 2160.0
 2260.0
 2450.0
 2550.0
!
! C. Minana Blasco. Afinacion de las marimbas en la costa pacifiica
! colombiana: Un ejemplo de la memoria intervalica africana en colombia.
! 1990
!
! [info]
! source = DaMuSc
! measured_id = M0289
! ref_id = 51
! country = Colombia
