! Colombia_Marimba_1.scl
!
Measured scale M0284 in DaMuSc
 16
!
 70.0
 330.0
 420.0
 575.0
 780.0
 900.0
 1070.0
 1275.0
 1380.0
 1560.0
 1760.0
 1880.0
 2070.0
 2240.0
 2400.0
 2590.0
!
! C. Mi+APE-ana Blasco. Afinacion de las marimbas en la costa pacifiica
! colombiana: Un ejemplo de la memoria intervalica africana en colombia.
! 1990
!
! [info]
! source = DaMuSc
! measured_id = M0284
! ref_id = 51
