! Colombia_Marimba_3.scl
!
Measured scale M0286 in DaMuSc
 19
!
 140.0
 285.0
 425.0
 585.0
 785.0
 925.0
 1105.0
 1265.0
 1405.0
 1555.0
 1745.0
 1900.0
 2045.0
 2265.0
 2400.0
 2555.0
 2725.0
 2905.0
 3105.0
!
! C. Mi+APE-ana Blasco. Afinacion de las marimbas en la costa pacifiica
! colombiana: Un ejemplo de la memoria intervalica africana en colombia.
! 1990
!
! [info]
! source = DaMuSc
! measured_id = M0286
! ref_id = 51
