! Colombia_Marimba_8.scl
!
Measured scale M0291 in DaMuSc
 17
!
 205.0
 335.0
 500.0
 695.0
 840.0
 1025.0
 1145.0
 1295.0
 1430.0
 1575.0
 1815.0
 1980.0
 2125.0
 2310.0
 2490.0
 2595.0
 2730.0
!
! C. Mi+APE-ana Blasco. Afinacion de las marimbas en la costa pacifiica
! colombiana: Un ejemplo de la memoria intervalica africana en colombia.
! 1990
!
! [info]
! source = DaMuSc
! measured_id = M0291
! ref_id = 51
