! Congo_Xylophone.scl
!
Measured scale M0226 in DaMuSc
 10
!
 209.0
 416.0
 686.0
 926.0
 1144.0
 1213.0
 1377.0
 1630.0
 1926.0
 2125.0
!
! R. Brandel. The Music of Central Africa: An Ethnomusicological Study:
! Former French Equatorial Africa the Former Belgian Congo, Ruanda-
! Urundi Uganda, Tanganyika. Springer Science and Business Media, 1967
!
! [info]
! source = DaMuSc
! measured_id = M0226
! ref_id = 6
