! DemRepCongo_Flute.scl
!
Measured scale M0222 in DaMuSc
 8
!
 204.0
 411.0
 710.0
 1000.0
 1206.0
 1409.0
 1918.0
 2321.0
!
! R. Brandel. The Music of Central Africa: An Ethnomusicological Study:
! Former French Equatorial Africa the Former Belgian Congo, Ruanda-
! Urundi Uganda, Tanganyika. Springer Science and Business Media, 1967
!
! [info]
! source = DaMuSc
! measured_id = M0222
! ref_id = 6
