! DemRepCongo_Xylophone.scl
!
Measured scale M0221 in DaMuSc
 10
!
 128.0
 317.0
 502.0
 699.0
 888.0
 1141.0
 1345.0
 1431.0
 1604.0
 1744.0
!
! R. Brandel. The Music of Central Africa: An Ethnomusicological Study:
! Former French Equatorial Africa the Former Belgian Congo, Ruanda-
! Urundi Uganda, Tanganyika. Springer Science and Business Media, 1967
!
! [info]
! source = DaMuSc
! measured_id = M0221
! ref_id = 6
