! DemRepCongo_Marimba_2.scl
!
Measured scale M0020 in DaMuSc
 17
!
 112.0
 338.0
 469.0
 646.0
 826.0
 972.0
 1187.0
 1352.0
 1476.0
 1691.0
 1849.0
 2033.0
 2239.0
 2405.0
 2557.0
 2737.0
 2891.0
!
! H. Rechberger. Scales and Modes Around the World: The Complete Guide
! to the Scales and Modes of the World. Fennica Gehrman Ltd., 2018
!
! [info]
! source = DaMuSc
! measured_id = M0020
! ref_id = 2
