! Ethiopia_Mus_05_Bati_Zafan.scl
!
Mus 5 Bati Zafan, Ethiopia
 5
!
 266.0
 535.0
 708.0
 1076.0
 1200.0 ! Octave added to measured scale
!
! Weisser, Stéphanie; Falceto, Francis (2013). Investigating qәñәt in
! Amhara secular music: an acoustic and historical study. Annales
! d'Ethiopie, 28(1):299-322.
!
! [info]
! source = DaMuSc
! measured_id = M0181
! ref_id = 40
! country = Ethiopia
! doi = https://doi.org/10.3406/ethio.2013.1539
