! Ethiopia_Mus_05_Yammatbal.scl
!
Mus 5 Yammatbal, Ethiopia
 5
!
 333.0
 505.0
 700.0
 1090.0
 1200.0 ! Octave added to measured scale
!
! Weisser, Stéphanie; Falceto, Francis (2013). Investigating qәñәt in
! Amhara secular music: an acoustic and historical study. Annales
! d'Ethiopie, 28(1):299-322.
!
! [info]
! source = DaMuSc
! measured_id = M0186
! ref_id = 40
! country = Ethiopia
! doi = https://doi.org/10.3406/ethio.2013.1539
