! Ethiopia_Mus_08_1976.scl
!
Mus 8 - 1976, Ethiopia
 5
!
 306.0
 498.0
 728.0
 1082.0
 1200.0 ! Octave added to measured scale
!
! Weisser, Stéphanie; Falceto, Francis (2013). Investigating qәñәt in
! Amhara secular music: an acoustic and historical study. Annales
! d'Ethiopie, 28(1):299-322.
!
! [info]
! source = DaMuSc
! measured_id = M0174
! ref_id = 40
! country = Ethiopia
! doi = https://doi.org/10.3406/ethio.2013.1539
