! Georgia_GVM207-H.scl
!
GVM207-H (Voice), Georgia
 6
!
 175.0
 368.0
 508.0
 697.0
 871.0
 1075.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0318
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
