! Georgia_GVM200-M.scl
!
GVM200-M (Voice), Georgia
 7
!
 208.0
 388.0
 570.0
 723.0
 865.0
 1038.0
 1210.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0314
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
