! Georgia_GVM201-H.scl
!
GVM201-H (Voice), Georgia
 7
!
 195.0
 346.0
 488.0
 690.0
 882.0
 1052.0
 1206.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0323
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
