! Georgia_GVM204-M.scl
!
GVM204-M (Voice), Georgia
 8
!
 202.0
 380.0
 562.0
 751.0
 931.0
 1099.0
 1265.0
 1412.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0317
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
