! Georgia_GVM202-M.scl
!
GVM202-M (Voice), Georgia
 7
!
 180.0
 383.0
 548.0
 735.0
 903.0
 1062.0
 1260.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0315
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
