! Georgia_GVM198-H.scl
!
GVM198-H (Voice), Georgia
 6
!
 393.0
 550.0
 714.0
 868.0
 1002.0
 1125.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0320
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
