! Georgia_GVM200-H.scl
!
GVM200-H (Voice), Georgia
 8
!
 174.0
 280.0
 390.0
 461.0
 651.0
 856.0
 981.0
 1081.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0325
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
