! Georgia_GVM208-M.scl
!
GVM208-M (Voice), Georgia
 7
!
 177.0
 355.0
 554.0
 722.0
 857.0
 1037.0
 1131.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0308
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
