! Georgia_GVM204-H.scl
!
GVM204-H (Voice), Georgia
 5
!
 345.0
 695.0
 850.0
 1059.0
 1184.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0328
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
