! Georgia_GVM203-H.scl
!
GVM203-H (Voice), Georgia
 8
!
 197.0
 345.0
 487.0
 691.0
 875.0
 968.0
 1052.0
 1173.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0327
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
