! Georgia_GVM208-H.scl
!
GVM208-H (Voice), Georgia
 5
!
 174.0
 362.0
 661.0
 816.0
 1011.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0319
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
