! Georgia_Average_All-M.scl
!
Measured scale M0302 in DaMuSc
 14
!
 197.0
 378.0
 551.0
 714.0
 898.0
 1073.0
 1240.0
 1406.0
 1602.0
 1784.0
 1949.0
 2129.0
 2309.0
 2498.0
!
! Frank Scherbaum, Nana Mzhavanadze, Simha Arom, Sebastian Rosenzweig,
! and Meinard Muller. Tonal Organization of the Erkomaishvili Dataset:
! Pitches, Scales, Melodies and Harmonies.
!
! [info]
! source = DaMuSc
! measured_id = M0302
! ref_id = 55
