! Georgia_GVM199-M.scl
!
GVM199-M (Voice), Georgia
 8
!
 121.0
 289.0
 457.0
 633.0
 803.0
 977.0
 1150.0
 1260.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0313
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
