! Georgia_GVM205-M.scl
!
GVM205-M (Voice), Georgia
 7
!
 174.0
 357.0
 548.0
 704.0
 882.0
 1065.0
 1201.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0310
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
