! Georgia_GVM206-M.scl
!
GVM206-M (Voice), Georgia
 7
!
 179.0
 358.0
 500.0
 701.0
 887.0
 1067.0
 1189.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0311
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
