! Georgia_GVM207-M.scl
!
GVM207-M (Voice), Georgia
 6
!
 192.0
 374.0
 584.0
 746.0
 882.0
 1060.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0307
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
