! Georgia_GCH-ID_008_All-H.scl
!
Measured scale M0301 in DaMuSc
 12
!
 173.0
 366.0
 535.0
 702.0
 901.0
 1071.0
 1235.0
 1405.0
 1596.0
 1783.0
 1919.0
 2306.0
!
! Frank Scherbaum, Nana Mzhavanadze, Simha Arom, Sebastian Rosenzweig,
! and Meinard Muller. Tonal Organization of the Erkomaishvili Dataset:
! Pitches, Scales, Melodies and Harmonies.
!
! [info]
! source = DaMuSc
! measured_id = M0301
! ref_id = 55
