! Georgia_GCH-ID_008_All-M.scl
!
Measured scale M0300 in DaMuSc
 12
!
 173.0
 364.0
 523.0
 717.0
 897.0
 1060.0
 1232.0
 1430.0
 1622.0
 1774.0
 1953.0
 2121.0
!
! Frank Scherbaum, Nana Mzhavanadze, Simha Arom, Sebastian Rosenzweig,
! and Meinard Muller. Tonal Organization of the Erkomaishvili Dataset:
! Pitches, Scales, Melodies and Harmonies.
!
! [info]
! source = DaMuSc
! measured_id = M0300
! ref_id = 55
