! Georgia_GVM203-M.scl
!
GVM203-M (Voice), Georgia
 8
!
 169.0
 347.0
 512.0
 687.0
 857.0
 1029.0
 1195.0
 1362.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0316
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
