! Greece_Grave.scl
!
Grave (Voice), Greece
 6
!
 200.0
 373.0
 490.0
 684.0
 891.0
 1202.0
!
! Panteli, Maria; Purwins, Hendrik (2013). A Quantitative Comparison of
! Chrysanthine Theory and Performance Practice of Scale Tuning, Steps,
! and Prominence of the Octoechos in Byzantine Chant. Journal of New
! Music Research, 42(3):205-221.
!
! [info]
! source = DaMuSc
! measured_id = M0432
! ref_id = 60
! country = Greece
! doi = https://doi.org/10.1080/09298215.2013.827215
