! Greece_Fourth.scl
!
Measured scale M0433 in DaMuSc
 7
!
 139.0
 339.0
 528.0
 661.0
 845.0
 1073.0
 1201.0
!
! Maria Panteli and Hendrik Purwins. A quantitative comparison of
! chrysanthine theory and performance practice of scale tuning, steps,
! and prominence of the octoechos in byzantine chant. J. New Music Res.,
! 42(3):205-221, 2013. doi: 10.1080/09298215. 2013.827215
!
! [info]
! source = DaMuSc
! measured_id = M0433
! ref_id = 60
