! Greece_First_Plagal.scl
!
First Plagal (Voice), Greece
 7
!
 195.0
 295.0
 500.0
 706.0
 818.0
 1001.0
 1201.0
!
! Panteli, Maria; Purwins, Hendrik (2013). A Quantitative Comparison of
! Chrysanthine Theory and Performance Practice of Scale Tuning, Steps,
! and Prominence of the Octoechos in Byzantine Chant. Journal of New
! Music Research, 42(3):205-221.
!
! [info]
! source = DaMuSc
! measured_id = M0428
! ref_id = 60
! country = Greece
! doi = https://doi.org/10.1080/09298215.2013.827215
