! Greece_First.scl
!
Measured scale M0427 in DaMuSc
 7
!
 150.0
 311.0
 510.0
 700.0
 822.0
 1005.0
 1199.0
!
! Maria Panteli and Hendrik Purwins. A quantitative comparison of
! chrysanthine theory and performance practice of scale tuning, steps,
! and prominence of the octoechos in byzantine chant. J. New Music Res.,
! 42(3):205-221, 2013. doi: 10.1080/09298215. 2013.827215
!
! [info]
! source = DaMuSc
! measured_id = M0427
! ref_id = 60
