! Greece_Fourth.scl
!
Fourth (Voice), Greece
 7
!
 139.0
 339.0
 528.0
 661.0
 845.0
 1073.0
 1201.0
!
! Panteli, Maria; Purwins, Hendrik (2013). A Quantitative Comparison of
! Chrysanthine Theory and Performance Practice of Scale Tuning, Steps,
! and Prominence of the Octoechos in Byzantine Chant. Journal of New
! Music Research, 42(3):205-221.
!
! [info]
! source = DaMuSc
! measured_id = M0433
! ref_id = 60
! country = Greece
! doi = https://doi.org/10.1080/09298215.2013.827215
