! Greece_Second.scl
!
Measured scale M0429 in DaMuSc
 7
!
 139.0
 361.0
 493.0
 710.0
 854.0
 1017.0
 1200.0
!
! Maria Panteli and Hendrik Purwins. A quantitative comparison of
! chrysanthine theory and performance practice of scale tuning, steps,
! and prominence of the octoechos in byzantine chant. J. New Music Res.,
! 42(3):205-221, 2013. doi: 10.1080/09298215. 2013.827215
!
! [info]
! source = DaMuSc
! measured_id = M0429
! ref_id = 60
