! Greece_Grave.scl
!
Measured scale M0432 in DaMuSc
 6
!
 200.0
 373.0
 490.0
 684.0
 891.0
 1202.0
!
! Maria Panteli and Hendrik Purwins. A quantitative comparison of
! chrysanthine theory and performance practice of scale tuning, steps,
! and prominence of the octoechos in byzantine chant. J. New Music Res.,
! 42(3):205-221, 2013. doi: 10.1080/09298215. 2013.827215
!
! [info]
! source = DaMuSc
! measured_id = M0432
! ref_id = 60
