! Greece_First_Plagal.scl
!
Measured scale M0428 in DaMuSc
 7
!
 195.0
 295.0
 500.0
 706.0
 818.0
 1001.0
 1201.0
!
! Maria Panteli and Hendrik Purwins. A quantitative comparison of
! chrysanthine theory and performance practice of scale tuning, steps,
! and prominence of the octoechos in byzantine chant. J. New Music Res.,
! 42(3):205-221, 2013. doi: 10.1080/09298215. 2013.827215
!
! [info]
! source = DaMuSc
! measured_id = M0428
! ref_id = 60
