! Greece_Fourth_Plagal.scl
!
Measured scale M0434 in DaMuSc
 7
!
 222.0
 378.0
 517.0
 718.0
 917.0
 1089.0
 1200.0
!
! Maria Panteli and Hendrik Purwins. A quantitative comparison of
! chrysanthine theory and performance practice of scale tuning, steps,
! and prominence of the octoechos in byzantine chant. J. New Music Res.,
! 42(3):205-221, 2013. doi: 10.1080/09298215. 2013.827215
!
! [info]
! source = DaMuSc
! measured_id = M0434
! ref_id = 60
