! Greece_Fourth_Plagal.scl
!
Fourth Plagal (Voice), Greece
 7
!
 222.0
 378.0
 517.0
 718.0
 917.0
 1089.0
 1200.0
!
! Panteli, Maria; Purwins, Hendrik (2013). A Quantitative Comparison of
! Chrysanthine Theory and Performance Practice of Scale Tuning, Steps,
! and Prominence of the Octoechos in Byzantine Chant. Journal of New
! Music Research, 42(3):205-221.
!
! [info]
! source = DaMuSc
! measured_id = M0434
! ref_id = 60
! country = Greece
! doi = https://doi.org/10.1080/09298215.2013.827215
