! Greece_First.scl
!
First (Voice), Greece
 7
!
 150.0
 311.0
 510.0
 700.0
 822.0
 1005.0
 1199.0
!
! Panteli, Maria; Purwins, Hendrik (2013). A Quantitative Comparison of
! Chrysanthine Theory and Performance Practice of Scale Tuning, Steps,
! and Prominence of the Octoechos in Byzantine Chant. Journal of New
! Music Research, 42(3):205-221.
!
! [info]
! source = DaMuSc
! measured_id = M0427
! ref_id = 60
! country = Greece
! doi = https://doi.org/10.1080/09298215.2013.827215
