! Guinea_Malinke_03.scl
!
Guinea Malinke 3 (Xylophone), Guinea
 17
!
 167.0
 347.0
 513.0
 679.0
 839.0
 1019.0
 1199.0
 1369.0
 1536.0
 1707.0
 1874.0
 2052.0
 2228.0
 2406.0
 2567.0
 2735.0
 2929.0
!
! Rouget, Gilbert; Schwarz, J. (1969). Sur les xylophones
! equiheptaphoniques des Malinke. Revue de musicologie, 55(1):47.
!
! [info]
! source = DaMuSc
! measured_id = M0133
! ref_id = 8
! country = Guinea
! doi = https://doi.org/10.2307/927751
