! Indonesia_Kanyutmesem_a.scl
!
Kanyutmesem (Saron Demung or Gender Barung), Indonesia
 7
!
 141.0
 281.0
 553.0
 692.0
 806.0
 978.0
 1223.0
!
! W. Surjodiningrat, A. Susanto, and P. J. Sudarjana. Tone Measurements
! of Outstanding Javanese Gamelans in Jogjakarta and Surakarta. Gadjah
! Mada University Press, 1972
!
! [info]
! source = DaMuSc
! measured_id = M0344
! ref_id = 12
! country = Indonesia
