! Indonesia_Gamelan_Kyai_Kaduk_Manis_Slendro.scl
!
Gamelan Kyai Kaduk Manis Slendro (Many Gamelan), Indonesia
 17
!
 266.0
 486.0
 719.0
 958.0
 1204.0
 1457.0
 1694.0
 1931.0
 2168.0
 2402.0
 2652.0
 2895.0
 3138.0
 3362.0
 3607.0
 3850.0
 4087.0
!
! Sethares (2005). Tuning, Timbre, Spectrum, Scale. Springer-Verlag.
!
! [info]
! source = DaMuSc
! measured_id = M0074
! ref_id = 30
! country = Indonesia
! doi = https://doi.org/10.1007/b138848
