! Indonesia_Gam_GPH_Hangabehi.scl
!
Gam. GPH Hangabehi (Saron Demung or Gender Barung), Indonesia
 5
!
 236.0
 469.0
 723.0
 960.0
 1212.0
!
! W. Surjodiningrat, A. Susanto, and P. J. Sudarjana. Tone Measurements
! of Outstanding Javanese Gamelans in Jogjakarta and Surakarta. Gadjah
! Mada University Press, 1972
!
! [info]
! source = DaMuSc
! measured_id = M0387
! ref_id = 12
! country = Indonesia
