! Indonesia_Gamelan_Swastigitha_Slendro.scl
!
Gamelan Swastigitha Slendro (Many Gamelan), Indonesia
 17
!
 191.0
 443.0
 682.0
 926.0
 1169.0
 1408.0
 1640.0
 1889.0
 2132.0
 2367.0
 2612.0
 2846.0
 3094.0
 3332.0
 3583.0
 3820.0
 4075.0
!
! Sethares (2005). Tuning, Timbre, Spectrum, Scale. Springer-Verlag.
!
! [info]
! source = DaMuSc
! measured_id = M0073
! ref_id = 30
! country = Indonesia
! doi = https://doi.org/10.1007/b138848
