! Indonesia_13.scl
!
Measured scale M0072 in DaMuSc
 5
!
 230.0
 481.0
 713.0
 958.0
 1224.0
!
! Edward C. Carterette, Roger A. Kendall, and Sue Carole De Vale.
! Comparative acoustical and psychoacoustical analyses of gamelan
! instrument tones. Journal of the Acoustical Society of Japan (E),
! 14(6):383-396, 1993. doi: 10.1250/ast.14.383
!
! [info]
! source = DaMuSc
! measured_id = M0072
! ref_id = 26
