! Indonesia_Radio_Republik_Indonesia_Sala.scl
!
Radio Republik Indonesia Sala (Saron Demung or Gender Barung), Indonesia
 7
!
 81.0
 242.0
 564.0
 675.0
 802.0
 937.0
 1227.0
!
! W. Surjodiningrat, A. Susanto, and P. J. Sudarjana. Tone Measurements
! of Outstanding Javanese Gamelans in Jogjakarta and Surakarta. Gadjah
! Mada University Press, 1972
!
! [info]
! source = DaMuSc
! measured_id = M0348
! ref_id = 12
! country = Indonesia
