! Indonesia_Konservatori_Karawitan_Gamelan_II_b.scl
!
Konservatori Karawitan Gamelan II (Saron Demung or Gender Barung), Indonesia
 5
!
 227.0
 473.0
 732.0
 976.0
 1216.0
!
! W. Surjodiningrat, A. Susanto, and P. J. Sudarjana. Tone Measurements
! of Outstanding Javanese Gamelans in Jogjakarta and Surakarta. Gadjah
! Mada University Press, 1972
!
! [info]
! source = DaMuSc
! measured_id = M0385
! ref_id = 12
! country = Indonesia
