! Indonesia_Madukusuma.scl
!
Madukusuma (Saron Demung or Gender Barung), Indonesia
 7
!
 121.0
 251.0
 554.0
 690.0
 796.0
 937.0
 1216.0
!
! W. Surjodiningrat, A. Susanto, and P. J. Sudarjana. Tone Measurements
! of Outstanding Javanese Gamelans in Jogjakarta and Surakarta. Gadjah
! Mada University Press, 1972
!
! [info]
! source = DaMuSc
! measured_id = M0354
! ref_id = 12
! country = Indonesia
