! Indonesia_12.scl
!
Measured scale M0071 in DaMuSc
 5
!
 228.0
 485.0
 717.0
 967.0
 1228.0
!
! Edward C. Carterette, Roger A. Kendall, and Sue Carole De Vale.
! Comparative acoustical and psychoacoustical analyses of gamelan
! instrument tones. Journal of the Acoustical Society of Japan (E),
! 14(6):383-396, 1993. doi: 10.1250/ast.14.383
!
! [info]
! source = DaMuSc
! measured_id = M0071
! ref_id = 26
