! Malawi_Asena_30.scl
!
Asena 30 (Malimba), Malawi
 17
!
 190.0
 316.0
 433.0
 595.0
 671.0
 815.0
 996.0
 1082.0
 1145.0
 1352.0
 1523.0
 1626.0
 1880.0
 1975.0
 2228.0
 2440.0
 2568.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0123
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
