! Malawi_Asena_17.scl
!
Asena 17 (Valimba), Malawi
 15
!
 202.0
 441.0
 617.0
 744.0
 958.0
 1097.0
 1250.0
 1434.0
 1641.0
 1825.0
 2008.0
 2158.0
 2323.0
 2474.0
 2613.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0110
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
