! Malawi_Asena_18.scl
!
Asena 18 (Valimba), Malawi
 16
!
 201.0
 337.0
 544.0
 711.0
 847.0
 1003.0
 1173.0
 1401.0
 1537.0
 1744.0
 1928.0
 2111.0
 2261.0
 2453.0
 2577.0
 2693.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0111
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
