! Malawi_Asena_06.scl
!
Asena 6 (Bangwe), Malawi
 12
!
 227.0
 368.0
 526.0
 658.0
 873.0
 1024.0
 1273.0
 1459.0
 1583.0
 1780.0
 1933.0
 2096.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0099
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
