! Malawi_Asena_10.scl
!
Asena 10 (Valimba), Malawi
 15
!
 154.0
 397.0
 547.0
 702.0
 860.0
 1092.0
 1219.0
 1404.0
 1592.0
 1779.0
 1975.0
 2126.0
 2285.0
 2455.0
 2604.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0103
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
