! Malawi_Asena_25.scl
!
Asena 25 (Valimba), Malawi
 14
!
 238.0
 417.0
 570.0
 752.0
 925.0
 1068.0
 1275.0
 1481.0
 1627.0
 1806.0
 2001.0
 2133.0
 2400.0
 2547.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0118
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
