! Malawi_Asena_24.scl
!
Asena 24 (Valimba), Malawi
 13
!
 255.0
 428.0
 630.0
 798.0
 951.0
 1135.0
 1283.0
 1437.0
 1677.0
 1801.0
 1971.0
 2126.0
 2291.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0117
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
