! Malawi_Asena_20.scl
!
Asena 20 (Valimba), Malawi
 15
!
 199.0
 355.0
 499.0
 649.0
 869.0
 1093.0
 1200.0
 1399.0
 1597.0
 1794.0
 1954.0
 2116.0
 2264.0
 2374.0
 2477.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0113
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
