! Malawi_Asena_02.scl
!
Asena 2 (Bangwe), Malawi
 12
!
 143.0
 309.0
 468.0
 648.0
 829.0
 994.0
 1180.0
 1334.0
 1509.0
 1668.0
 1841.0
 2023.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0095
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
