! Malawi_Asena_16.scl
!
Asena 16 (Valimba), Malawi
 15
!
 131.0
 274.0
 445.0
 635.0
 798.0
 1023.0
 1189.0
 1366.0
 1558.0
 1710.0
 1804.0
 1977.0
 2254.0
 2377.0
 2524.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0109
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
