! Malawi_Asena_03.scl
!
Asena 3 (Bangwe), Malawi
 10
!
 161.0
 403.0
 540.0
 771.0
 901.0
 1135.0
 1263.0
 1442.0
 1596.0
 1772.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0096
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
