! Malawi_Asena_11.scl
!
Asena 11 (Valimba), Malawi
 12
!
 136.0
 287.0
 469.0
 686.0
 809.0
 1010.0
 1191.0
 1371.0
 1519.0
 1713.0
 1808.0
 2009.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0104
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
