! Malawi_Asena_13.scl
!
Asena 13 (Valimba), Malawi
 17
!
 143.0
 316.0
 511.0
 669.0
 837.0
 991.0
 1144.0
 1337.0
 1526.0
 1706.0
 1923.0
 2075.0
 2232.0
 2406.0
 2537.0
 2741.0
 2919.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0106
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
