! Malawi_Asena_21.scl
!
Asena 21 (Valimba), Malawi
 12
!
 184.0
 398.0
 575.0
 734.0
 904.0
 1079.0
 1200.0
 1384.0
 1567.0
 1717.0
 1934.0
 2104.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0114
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
