! Malawi_Asena_22.scl
!
Asena 22 (Valimba), Malawi
 16
!
 199.0
 376.0
 537.0
 667.0
 821.0
 1035.0
 1200.0
 1375.0
 1555.0
 1757.0
 1937.0
 2085.0
 2293.0
 2452.0
 2622.0
 2733.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0115
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
