! Malawi_Asena_15.scl
!
Asena 15 (Valimba), Malawi
 15
!
 179.0
 341.0
 536.0
 660.0
 808.0
 987.0
 1150.0
 1322.0
 1499.0
 1698.0
 1860.0
 2039.0
 2243.0
 2425.0
 2545.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0108
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
