! Malawi_Asena_04.scl
!
Asena 4 (Bangwe), Malawi
 10
!
 210.0
 382.0
 567.0
 708.0
 888.0
 1072.0
 1279.0
 1446.0
 1614.0
 1767.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0097
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
