! Malawi_Asena_12.scl
!
Asena 12 (Valimba), Malawi
 15
!
 218.0
 349.0
 530.0
 675.0
 794.0
 1008.0
 1200.0
 1348.0
 1528.0
 1730.0
 1893.0
 2058.0
 2208.0
 2347.0
 2524.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0105
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
