! Malawi_Asena_01.scl
!
Asena 1 (Bangwe), Malawi
 11
!
 243.0
 379.0
 554.0
 755.0
 936.0
 1116.0
 1295.0
 1443.0
 1579.0
 1730.0
 1912.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0094
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
