! Mozambique_Mambira.scl
!
Measured scale M0277 in DaMuSc
 16
!
 379.0
 513.0
 740.0
 876.0
 1108.0
 1358.0
 1496.0
 1694.0
 1816.0
 1937.0
 2112.0
 2256.0
 2416.0
 2545.0
 2854.0
 4254.0
!
! G. Kubik. Discovery of a trough xylophone in northern mozambique.
! African Music : Journal of the International Library of African Music,
! 3(2):11-14, 1963. doi: https://doi.org/10.21504/amj.v3i2.826
!
! [info]
! source = DaMuSc
! measured_id = M0277
! ref_id = 48
