! Mozambique_Mambira.scl
!
Mambira (Mambira), Mozambique
 16
!
 379.0
 513.0
 740.0
 876.0
 1108.0
 1358.0
 1496.0
 1694.0
 1816.0
 1937.0
 2112.0
 2256.0
 2416.0
 2545.0
 2854.0
 4254.0
!
! Kubik, Gerhard (1963). Discovery of a trough xylophone in northern
! Mozambique. African Music: Journal of the African Music Society,
! 3(2):11-14.
!
! [info]
! source = DaMuSc
! measured_id = M0277
! ref_id = 48
! country = Mozambique
! doi = https://doi.org/10.21504/amj.v3i2.826
