! Solomon_Islands_Panpipe_03.scl
!
Panpipe 3 (Panpipe), Solomon Islands
 15
!
 200.0
 411.0
 644.0
 838.0
 1011.0
 1211.0
 1412.0
 1598.0
 1777.0
 1931.0
 2124.0
 2240.0
 2399.0
 2561.0
 2809.0
!
! H. Rechberger. Scales and Modes Around the World: The Complete Guide
! to the Scales and Modes of the World. Fennica Gehrman Ltd., 2018
!
! [info]
! source = DaMuSc
! measured_id = M0047
! ref_id = 2
! country = Solomon Islands
