! Tanzania_Sanza.scl
!
Measured scale M0235 in DaMuSc
 9
!
 401.0
 699.0
 902.0
 1095.0
 1200.0
 1403.0
 1601.0
 1701.0
 1895.0
!
! R. Brandel. The Music of Central Africa: An Ethnomusicological Study:
! Former French Equatorial Africa the Former Belgian Congo, Ruanda-
! Urundi Uganda, Tanganyika. Springer Science and Business Media, 1967
!
! [info]
! source = DaMuSc
! measured_id = M0235
! ref_id = 6
