! Thailand_8.scl
!
Measured scale M0067 in DaMuSc
 7
!
 162.0
 310.0
 446.0
 613.0
 746.0
 970.0
 1124.0
!
! K. Attakitmongcol, R. Chinvejkitvanich, and S. Sujitjorn.
! Characterization of traditional thai musical scale. In Proceedings of
! the 5th WSEAS International Conference on Acoustics and Music: Theory
! and Applications (AMTA04), 2004
!
! [info]
! source = DaMuSc
! measured_id = M0067
! ref_id = 28
