! Thailand_7.scl
!
Measured scale M0066 in DaMuSc
 13
!
 173.0
 345.0
 515.0
 649.0
 852.0
 1028.0
 1200.0
 1375.0
 1544.0
 1713.0
 1887.0
 2055.0
 2225.0
!
! A. Morkonr, S. Punkubutra, et al. The collecting process of
! xylophone's sound d (ranad xek) from art to numerical data. In 2018
! International Conference on Engineering, Applied Sciences, and
! Technology (ICEAST), pages 1-4, 2018. doi: 10.1109/
! ICEAST.2018.8434434
!
! [info]
! source = DaMuSc
! measured_id = M0066
! ref_id = 36
