! Thailand_9.scl
!
Measured scale M0068 in DaMuSc
 7
!
 188.0
 358.0
 513.0
 683.0
 846.0
 1027.0
 1205.0
!
! K. Attakitmongcol, R. Chinvejkitvanich, and S. Sujitjorn.
! Characterization of traditional thai musical scale. In Proceedings of
! the 5th WSEAS International Conference on Acoustics and Music: Theory
! and Applications (AMTA04), 2004
!
! [info]
! source = DaMuSc
! measured_id = M0068
! ref_id = 28
