! Zimbabwe_Matepe_01.scl
!
Matepe 1 (Mbira), Zimbabwe
 11
!
 154.0
 369.0
 867.0
 1032.0
 1218.0
 1386.0
 1568.0
 1746.0
 1884.0
 2066.0
 2251.0
!
! Tracey, Andrew (1970). The Matepe mbira music of Rhodesia. African
! Music: Journal of the African Music Society, 4(4):37-61.
!
! [info]
! source = DaMuSc
! measured_id = M0127
! ref_id = 9
! country = Zimbabwe
! doi = https://doi.org/10.21504/amj.v4i4.1681
