! xen03-wilson-positive-29.scl
!
Positive, linear-mapped intonational system, 29 notes
 29
!
 28/27
 256/243
 16/15
 10/9
 9/8
 7/6
 32/27
 6/5
 5/4
 81/64
 21/16
 4/3
 112/81
 1024/729
 64/45
 40/27
 3/2
 14/9
 128/81
 8/5
 5/3
 27/16
 7/4
 16/9
 9/5
 15/8
 243/128
 63/32
 2/1
!
! Erv Wilson
! On the development of intonational systems by extended linear mapping
! Xenharmonikon 3 (1975)
!
! Diagram 5
!
! [info]
! source = Xenharmonikon
! whole_number = 3
