! xen03-wilson-negative-31.scl
!
Negative, linear-mapped intonational system, 31 notes
 31
!
 64/63
 28/27
 16/15
 12/11
 9/8
 8/7
 7/6
 6/5
 27/22
 5/4
 80/63
 35/27
 4/3
 256/189
 112/81
 64/45
 16/11
 3/2
 32/21
 14/9
 8/5
 18/11
 27/16
 12/7
 7/4
 9/5
 81/44
 15/8
 40/21
 35/18
 2/1
!
! Erv Wilson
! On the development of intonational systems by extended linear mapping
! Xenharmonikon 3 (1975)
!
! Diagrams 4 and 7
!
! [info]
! source = Xenharmonikon
! whole_number = 3
