! xen03-wilson-acute-22.scl
!
Acute, linear-mapped intonational system, 22 notes
 22
!
 28/27
 16/15
 10/9
 9/8
 7/6
 6/5
 5/4
 35/27
 4/3
 112/81
 64/45
 40/27
 3/2
 14/9
 8/5
 5/3
 27/16
 7/4
 9/5
 15/8
 35/18
 2/1
!
! Erv Wilson
! On the development of intonational systems by extended linear mapping
! Xenharmonikon 3 (1975)
!
! Diagrams 6 and 9
!
! [info]
! source = Xenharmonikon
! whole_number = 3
