! xen18-erlich-ripple-11.scl
!
1L 10s MOS for Ripple, L=183.42, s=101.99
 11
!
 101.99  ! s
 203.98  ! s
 305.97  ! s
 407.96  ! s
 509.95  ! s
 693.37  ! L
 795.36  ! s
 897.35  ! s
 999.34  ! s
 1101.33 ! s
 1203.32 ! s
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.196
!
! [info]
! source = Xenharmonikon
! whole_number = 18
