! xen11-chalmers-tetrachordal-10-03.scl
!
Prime-Prime and Inverted-Inverted Heptatonic Diamonds, 27 Tones
 27
!
 36/35
 28/27
 16/15
 9/8
 7/6
 6/5
 5/4
 9/7
 35/27
 4/3
 48/35
 112/81
 45/32
 64/45
 81/56
 35/24
 3/2
 54/35
 14/9
 8/5
 5/3
 12/7
 16/9
 15/8
 27/14
 35/18
 2/1
!
! John H. Chalmers, Jr.
! Tetrachordal Scales and Complexes
! Xenharmonikon 11 (1988)
!
! [info]
! source = Xenharmonikon
! whole_number = 11
