! xen18-erlich-meantone-12.scl
!
7L 5s MOS for Meantone, L=117.25, s=76.19
 12
!
 117.25  ! L
 193.44  ! s
 310.69  ! L
 386.88  ! s
 504.13  ! L
 580.32  ! s
 697.57  ! L
 814.82  ! L
 891.01  ! s
 1008.26 ! L
 1084.45 ! s
 1201.70 ! L
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.190
!
! [info]
! source = Xenharmonikon
! whole_number = 18
