! xen18-schulter-pure-11-14.scl
!
Temperament with pure 11:14 major thirds, fifth of 704.377 cents
 12
!
 130.64  ! C#
 208.75  ! D
 286.87  ! Eb
 417.51  ! E, 14:11
 495.62  ! F
 626.26  ! F#
 704.38  ! G
 835.02  ! G#, 196:121
 913.13  ! A
 991.25  ! Bb
 1121.88 ! B
 1200.0  ! C, 2:1
!
! Margo Schulter
! George Secor's 17-Tone Well-Temperament and Neo-Medieval Music
! Xenharmonikon 18 (2006), p.85
!
! [info]
! source = Xenharmonikon
! whole_number = 18
