! xen18-erlich-vishnu-16.scl
!
2L 14s MOS for Vishnu, L=101.92, s=71.15
 16
!
 71.15   ! s
 142.30  ! s
 213.45  ! s
 315.37  ! L
 386.52  ! s
 457.67  ! s
 528.82  ! s
 599.97  ! s
 671.12  ! s
 742.27  ! s
 813.42  ! s
 915.34  ! L
 986.49  ! s
 1057.64 ! s
 1128.79 ! s
 1199.94 ! s
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.199
!
! [info]
! source = Xenharmonikon
! whole_number = 18
