! xen18-erlich-srutal-12.scl
!
10L 2s MOS for Srutal, L=104.70, s=76.06
 12
!
 104.70  ! L
 209.40  ! L
 314.10  ! L
 390.16  ! s
 494.86  ! L
 599.56  ! L
 704.26  ! L
 808.96  ! L
 913.66  ! L
 989.72  ! s
 1094.42 ! L
 1199.12 ! L
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.198
!
! [info]
! source = Xenharmonikon
! whole_number = 18
