! xen15-chalmers-triadic-reversed-diamond-23-20-tetrachord.scl
!
Tetrachord 23/20 * 1600/1587 * 23/20 of triadic reversed diamond for M=23/20, D=3/2
 3
!
 23/20
 80/69
 4/3
!
! John H. Chalmers, Jr.
! The Triadic Diamond, the Triadic Reversed Diamond, and their Constituent Tetrachords when D=3/2
! Xenharmonikon 15 (1993), p.66
!
! [info]
! source = Xenharmonikon
! whole_number = 15
! article = triadic
