! xen18-erlich-liese-17.scl
!
2L 15s MOS for Liese, L=117.41, s=64.52
 17
!
 64.52   ! s
 129.04  ! s
 193.56  ! s
 258.08  ! s
 375.49  ! L
 440.01  ! s
 504.53  ! s
 569.05  ! s
 633.57  ! s
 698.09  ! s
 762.61  ! s
 827.13  ! s
 944.54  ! L
 1009.06 ! s
 1073.58 ! s
 1138.10 ! s
 1202.62 ! s
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.189
!
! [info]
! source = Xenharmonikon
! whole_number = 18
