! xen18-erlich-blacksmith-15.scl
!
10L 5s MOS for Blacksmith, L=83.83, s=71.52
 15
!
 83.83   ! L
 155.35  ! s
 239.18  ! L
 323.01  ! L
 394.53  ! s
 478.36  ! L
 562.19  ! L
 633.71  ! s
 717.54  ! L
 801.37  ! L
 872.89  ! s
 956.72  ! L
 1040.55 ! L
 1112.07 ! s
 1195.90 ! L
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.183
!
! [info]
! source = Xenharmonikon
! whole_number = 18
