! xen18-erlich-liese-13.scl
!
2L 11s MOS for Liese, L=246.45, s=64.52
 13
!
 64.52   ! s
 129.04  ! s
 193.56  ! s
 440.01  ! L
 504.53  ! s
 569.05  ! s
 633.57  ! s
 698.09  ! s
 762.61  ! s
 1009.06 ! L
 1073.58 ! s
 1138.10 ! s
 1202.62 ! s
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.189
!
! [info]
! source = Xenharmonikon
! whole_number = 18
