! xen18-erlich-wurschmidt-13.scl
!
3L 10s MOS for Wurschmidt, L=277.33, s=36.77
 13
!
 36.77   ! s
 73.54   ! s
 350.87  ! L
 387.64  ! s
 424.41  ! s
 461.18  ! s
 738.51  ! L
 775.28  ! s
 812.05  ! s
 848.82  ! s
 1126.15 ! L
 1162.92 ! s
 1199.69 ! s
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.199
!
! [info]
! source = Xenharmonikon
! whole_number = 18
