! xen12-wilson-15-diamond-eikosany-intersection.scl
!
Intersection of Diamond & Eikosany (1 3 5 7 9 11), Figure 15
 10
!
 7/6   ! 5*7*11
 14/11 ! 3*5*7
 4/3   ! 1*5*11
 7/5   ! 3*7*11
 16/11 ! 1*3*5
 3/2   ! 5*9*11
 8/5   ! 1*3*11
 18/11 ! 3*5*9
 9/5   ! 3*9*11
 2/1   ! 3*5*11
!
! Erv Wilson
! D'Alessandro, like a Hurricane
! Xenharmonikon 12 (1989)
!
! [info]
! source = Xenharmonikon
! whole_number = 12
