! xen18-erlich-catler-12.scl
!
12L MOS for Catler, L=99.81
 12
!
 99.81   ! L
 199.62  ! L
 299.43  ! L
 399.24  ! L
 499.05  ! L
 598.86  ! L
 698.67  ! L
 798.48  ! L
 898.29  ! L
 998.10  ! L
 1097.91 ! L
 1197.72 ! L
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.183
!
! [info]
! source = Xenharmonikon
! whole_number = 18
