! xen18-erlich-passion-13.scl
!
12L 1s MOS for Passion, L=98.40, s=17.51
 13
!
 98.40   ! L
 196.80  ! L
 295.20  ! L
 393.60  ! L
 492.00  ! L
 590.40  ! L
 607.91  ! s
 706.31  ! L
 804.71  ! L
 903.11  ! L
 1001.51 ! L
 1099.91 ! L
 1198.31 ! L
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.195
!
! [info]
! source = Xenharmonikon
! whole_number = 18
