! xen18-erlich-compton-12.scl
!
12L MOS for Compton, L=100.05
 12
!
 100.05  ! L
 200.10  ! L
 300.15  ! L
 400.20  ! L
 500.25  ! L
 600.30  ! L
 700.35  ! L
 800.40  ! L
 900.45  ! L
 1000.50 ! L
 1100.55 ! L
 1200.60 ! L
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.184
!
! [info]
! source = Xenharmonikon
! whole_number = 18
