! xen18-secor-17-wt.scl
!
Secor 17-tone Well Temperament
 17
!
 66.741   ! Db
 144.856  ! C#
 214.441  ! D
 278.339  ! Eb
 353.61   ! D#
 428.882  ! E
 492.78   ! F
 562.364  ! Gb
 640.479  ! F#
 707.22   ! G
 771.118  ! Ab
 849.233  ! G#
 921.661  ! A
 985.559  ! Bb
 1057.987 ! A#
 1136.102 ! B
 1200.0   ! C
!
! George Secor
! The 17-tone Puzzle - And the Neo-medieval Key that Unlocks It
! Xenharmonikon 18 (2006), p.79
!
! [info]
! source = Xenharmonikon
! whole_number = 18
