! xen18-erlich-sensisept-11.scl
!
8L 3s MOS for Sensisept, L=131.09, s=49.89
 11
!
 131.09  ! L
 180.98  ! s
 312.07  ! L
 443.16  ! L
 574.25  ! L
 624.14  ! s
 755.23  ! L
 886.32  ! L
 1017.41 ! L
 1067.30 ! s
 1198.39 ! L
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.197
!
! [info]
! source = Xenharmonikon
! whole_number = 18
