! xen18-erlich-nautilus-11.scl
!
1L 10s MOS for Nautilus, L=372.96, s=82.97
 11
!
 82.97   ! s
 165.94  ! s
 248.91  ! s
 331.88  ! s
 414.85  ! s
 787.81  ! L
 870.78  ! s
 953.75  ! s
 1036.72 ! s
 1119.69 ! s
 1202.66 ! s
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.192
!
! [info]
! source = Xenharmonikon
! whole_number = 18
