! xen18-erlich-superpyth-12.scl
!
5L 7s MOS for Superpyth, L=166.79, s=51.95
 12
!
 51.95   ! s
 218.74  ! L
 270.69  ! s
 437.48  ! L
 489.43  ! s
 541.38  ! s
 708.17  ! L
 760.12  ! s
 926.91  ! L
 978.86  ! s
 1145.65 ! L
 1197.60 ! s
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.198
!
! [info]
! source = Xenharmonikon
! whole_number = 18
