! xen18-erlich-dominant-12.scl
!
5L 7s MOS for Dominant, L=114.53, s=88.94
 12
!
 88.94   ! s
 203.47  ! L
 292.41  ! s
 406.94  ! L
 495.88  ! s
 610.41  ! L
 699.35  ! s
 788.29  ! s
 902.82  ! L
 991.76  ! s
 1106.29 ! L
 1195.23 ! s
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.185
!
! [info]
! source = Xenharmonikon
! whole_number = 18
