! xen18-erlich-passion-12.scl
!
1L 11s MOS for Passion, L=115.91, s=98.40
 12
!
 98.40   ! s
 196.80  ! s
 295.20  ! s
 393.60  ! s
 492.00  ! s
 607.91  ! L
 706.31  ! s
 804.71  ! s
 903.11  ! s
 1001.51 ! s
 1099.91 ! s
 1198.31 ! s
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.195
!
! [info]
! source = Xenharmonikon
! whole_number = 18
