! xen15-chalmers-triadic-diamond-8192-6561-tetrachord.scl
!
Upper tetrachord 2187/2048 * 134217728/129140163 * 19683/16384 of triadic diamond for M=8192/6561, D=3/2
 3
!
 2187/2048
 65536/59049
 4/3
!
! John H. Chalmers, Jr.
! The Triadic Diamond, the Triadic Reversed Diamond, and their Constituent Tetrachords when D=3/2
! Xenharmonikon 15 (1993), p.64
!
! [info]
! source = Xenharmonikon
! whole_number = 15
