! xen18-erlich-superpyth-17.scl
!
5L 12s MOS for Superpyth, L=114.84, s=51.95
 17
!
 51.95   ! s
 166.79  ! L
 218.74  ! s
 270.69  ! s
 322.64  ! s
 437.48  ! L
 489.43  ! s
 541.38  ! s
 656.22  ! L
 708.17  ! s
 760.12  ! s
 874.96  ! L
 926.91  ! s
 978.86  ! s
 1030.81 ! s
 1145.65 ! L
 1197.60 ! s
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.198
!
! [info]
! source = Xenharmonikon
! whole_number = 18
