! xen18-erlich-blackwood-15.scl
!
10L 5s MOS for Blackwood, L=80.09, s=78.69
 15
!
 80.09   ! L
 158.78  ! s
 238.87  ! L
 318.96  ! L
 397.65  ! s
 477.74  ! L
 557.83  ! L
 636.52  ! s
 716.61  ! L
 796.70  ! L
 875.39  ! s
 955.48  ! L
 1035.57 ! L
 1114.26 ! s
 1194.35 ! L
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.183
!
! [info]
! source = Xenharmonikon
! whole_number = 18
