! xen18-erlich-myna-15.scl
!
4L 11s MOS for Myna, L=187.70, s=40.73
 15
!
 40.73   ! s
 228.43  ! L
 269.16  ! s
 309.89  ! s
 350.62  ! s
 538.32  ! L
 579.05  ! s
 619.78  ! s
 660.51  ! s
 848.21  ! L
 888.94  ! s
 929.67  ! s
 970.40  ! s
 1158.10 ! L
 1198.83 ! s
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.191
!
! [info]
! source = Xenharmonikon
! whole_number = 18
