! xen18-erlich-orson-13.scl
!
9L 4s MOS for Orson, L=113.64, s=44.37
 13
!
 113.64  ! L
 158.01  ! s
 271.65  ! L
 385.29  ! L
 429.66  ! s
 543.30  ! L
 656.94  ! L
 770.58  ! L
 814.95  ! s
 928.59  ! L
 1042.23 ! L
 1086.60 ! s
 1200.24 ! L
!
! Paul Erlich
! A Middle Path Between Just Intonation and the Equal Temperaments Part 1
! Xenharmonikon 18 (2006), p.194
!
! [info]
! source = Xenharmonikon
! whole_number = 18
