! CD01_08_Egypt.scl
!
Il a circulé avec les coupes - Darwîsh Muhammad al-Harîrî (hijaz, Egypt)
 6
!
 201.611585
 354.840089
 499.862257
 695.327283
 889.737439
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 1
! track = 8
! mbid = bd15a679-3ded-4e5c-bb95-8e1cbd2c3860
! maqam = hijaz
! region = Egypt
! tonic_ref = lowest_peak
