! CD02_03_Egypt.scl
!
Par le grand mode Nahâwand - Darwîsh Muhammad al-Harîrî (nahawand, Egypt)
 7
!
 88.421275
 392.383314
 608.939861
 808.918683
 901.332347
 1111.09036
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 2
! track = 3
! mbid = 813a6db2-b69a-4b36-b5d1-c80ca4edce97
! maqam = nahawand
! region = Egypt
! tonic_ref = lowest_peak
