! CD02_08_Egypt.scl
!
Suite - Darwîsh Muhammad al-Harîrî (sikah arabi, Egypt)
 7
!
 90.083403
 318.343352
 454.763926
 606.002529
 811.474493
 1010.337931
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 2
! track = 8
! mbid = 4b8ff499-1cb4-4aae-8bd1-38a4cd223f65
! maqam = sikah arabi
! region = Egypt
! tonic_ref = lowest_peak
