! CD03_01_Egypt.scl
!
Lève-toi et suis - Darwîsh Muhammad al-Harîrî (ajam ushayran, Egypt)
 7
!
 195.216528
 325.03238
 500.908605
 697.788011
 920.473459
 989.944832
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 3
! track = 1
! mbid = d4a0bf58-da59-425a-9fd3-71f25b94674f
! maqam = ajam ushayran
! region = Egypt
! tonic_ref = lowest_peak
