! CD05_16_Egypt.scl
!
Gens de beauté et de pureté - ‘Abduh al-Ḥāmūlī (bayati, Egypt)
 7
!
 206.684207
 356.847267
 515.039739
 708.380281
 896.627604
 1060.369428
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 5
! track = 16
! mbid = bcebfda5-ca4f-4de4-87fc-4cd6b8fe4dc4
! maqam = bayati
! region = Egypt
! tonic_ref = lowest_peak
