! CD05_13_Egypt.scl
!
Sa taille ondoyante - ‘Abduh al-Ḥāmūlī (bayati, Egypt)
 6
!
 211.633481
 352.380211
 508.440567
 708.214039
 895.890411
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 5
! track = 13
! mbid = 4dc9416b-753c-45bb-8087-2771913f41d9
! maqam = bayati
! region = Egypt
! tonic_ref = lowest_peak
