! CD05_03_bayati_Egypt.scl
!
Suite - ‘Abduh al-Ḥāmūlī (bayati, Egypt)
 7
!
 149.343608
 302.260523
 506.564458
 630.852116
 876.060824
 1002.510558
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 5
! track = 3
! mbid = a21bc93b-87a8-48da-ac7e-d9347ab16e9c
! maqam = bayati
! region = Egypt
! tonic_ref = annotated
! tonic_hz = 126.15
