! CD06_05_Egypt.scl
!
Moi, l'égyptien / Ô vie de l'âme - Muhammad al-Bahr (ajam, Egypt)
 7
!
 210.719908
 402.426049
 597.500482
 707.745669
 915.61376
 1097.877666
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 6
! track = 5
! mbid = 269fc45d-bd33-4e90-a76f-17d4e49530d0
! maqam = ajam
! region = Egypt
! tonic_ref = lowest_peak
