! CD06_06_Egypt.scl
!
C'est ton jour, c'est ton heure - Muhammad al-Bahr (nahawand, Egypt)
 7
!
 191.036
 378.25969
 490.420159
 696.032776
 900.879298
 985.725211
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 6
! track = 6
! mbid = db256794-2ef3-4df4-bc1e-a0ca9b03fa49
! maqam = nahawand
! region = Egypt
! tonic_ref = lowest_peak
