! CD07_11_Egypt.scl
!
Danse, rythme Ayyûb - Taha Abû Mandûr (unknown maqam, Egypt)
 7
!
 102.887166
 351.097845
 485.425887
 704.204859
 873.663052
 964.722811
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 7
! track = 11
! mbid = cf39d41a-cf85-49be-8e85-cc82d2c54fe0
! region = Egypt
! tonic_ref = lowest_peak
