! CD07_02_Egypt.scl
!
Ô fille, de ton nom je ne sais rien / Nous commencerons par l'élégant - Les Bédouins du Fayyûm (unknown maqam, Egypt)
 5
!
 406.205029
 569.57345
 620.776458
 978.69964
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 7
! track = 2
! mbid = 13582ece-81ab-42d1-9bc5-96a0bb2acd49
! region = Egypt
! tonic_ref = lowest_peak
