! CD07_06_Egypt.scl
!
Suite - Les Bédouins du Fayyûm (unknown maqam, Egypt)
 4
!
 126.636614
 458.016598
 953.397411
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 7
! track = 6
! mbid = c49261c7-2f42-436d-b2fb-3d6ec1d33365
! region = Egypt
! tonic_ref = lowest_peak
