! CD07_05_Egypt.scl
!
Nage, ô Salîm, dans la citerne ! - Les Bédouins du Fayyûm (unknown maqam, Egypt)
 7
!
 114.160809
 195.799434
 533.565586
 602.86847
 699.058264
 940.656019
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 7
! track = 5
! mbid = 11b4a8d2-d032-4135-8a7b-1d017b6228cd
! region = Egypt
! tonic_ref = lowest_peak
