! CD07_15_Egypt.scl
!
Danse lente, rythme Zar'î - Taha Abû Mandûr (unknown maqam, Egypt)
 6
!
 193.485472
 498.747482
 713.194118
 847.486204
 1007.432513
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 7
! track = 15
! mbid = 65fc6193-ce7f-4b3a-a83a-44266117c1cf
! region = Egypt
! tonic_ref = lowest_peak
