! CD07_19_Egypt.scl
!
Toi qui apparais semblable à la pleine lune - Annûsa Al-Misriyya (nahawand, Egypt)
 5
!
 117.301775
 317.798491
 457.401619
 663.500051
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 7
! track = 19
! mbid = b9c74916-b88d-476d-90ae-7f8c78c30780
! maqam = nahawand
! region = Egypt
! tonic_ref = lowest_peak
