! CD07_18_Egypt.scl
!
Cette nuit, le henné - Annûsa Al-Misriyya (unknown maqam, Egypt)
 5
!
 337.82654
 490.819075
 669.46202
 953.217365
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 7
! track = 18
! mbid = 4c39104a-5f0d-4790-a994-f27df8c4427a
! region = Egypt
! tonic_ref = lowest_peak
