! CD07_01_Egypt.scl
!
Le rebelle d'autrefois s'est soumis - Les Bédouins du Fayyûm (unknown maqam, Egypt)
 6
!
 337.228571
 451.276803
 598.636364
 855.0
 1065.683761
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 7
! track = 1
! mbid = 946f3565-85c6-46fd-b51e-20c00ad47604
! region = Egypt
! tonic_ref = lowest_peak
