! CD08_08_bayati_Egypt.scl
!
Le troisième salut - Mustafa Fahreddin Dede (bayati, Egypt)
 6
!
 171.921947
 290.134141
 500.210167
 703.268719
 1001.863667
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 8
! track = 8
! mbid = debb3ef6-f46b-45a5-864b-f6c7f948fcf5
! maqam = bayati
! region = Egypt
! tonic_ref = annotated
! tonic_hz = 162.11
