! CD08_01_Egypt.scl
!
Ô Mawlânâ, ami de la vérité - Mustafa Fahreddin Dede (rast, Egypt)
 6
!
 264.496536
 490.122181
 696.681413
 811.903174
 992.374647
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 8
! track = 1
! mbid = 09eaa62f-1b7b-40eb-a306-f7590621f69a
! maqam = rast
! region = Egypt
! tonic_ref = lowest_peak
