! CD09_05_Egypt.scl
!
Accours te réfugier au sanctuaire - La Confrérie Laythiyya (unknown maqam, Egypt)
 8
!
 189.552383
 252.1752
 292.7489
 566.034955
 686.147434
 836.401449
 1060.539229
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 9
! track = 5
! mbid = d448bfa6-bd12-4ae8-8af4-1b5fedfd449f
! region = Egypt
! tonic_ref = lowest_peak
