! CD09_12_Egypt.scl
!
Rûmînajdî - Umm Ibrâhîm Al-Mahdiyya (unknown maqam, Egypt)
 6
!
 360.12045
 529.869843
 789.351852
 1023.75
 1107.638889
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 9
! track = 12
! mbid = 81f5d5c5-c858-413d-b99e-d1a433694b53
! region = Egypt
! tonic_ref = lowest_peak
