! CD09_04_Egypt.scl
!
Ô chamelier - La Confrérie Laythiyya (unknown maqam, Egypt)
 7
!
 145.985288
 314.641373
 348.715447
 503.882583
 621.571634
 974.342269
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 9
! track = 4
! mbid = 7e43fcaa-d277-4ec2-b3e7-e7bbe95a807d
! region = Egypt
! tonic_ref = lowest_peak
