! CD10_02_Egypt.scl
!
Salut à Marie / Bimâyro - Mîkhâ'îl Jirjis al-Batânûnî (unknown maqam, Egypt)
 6
!
 160.308589
 255.607316
 469.09374
 892.464556
 1017.200249
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 10
! track = 2
! mbid = 4c2da17a-08f1-4699-af31-fb7ae65b9a90
! region = Egypt
! tonic_ref = lowest_peak
