! CD10_09_Egypt.scl
!
Bénédiction des chérubins - Mîkhâ'îl Jirjis al-Batânûnî (unknown maqam, Egypt)
 6
!
 234.591053
 498.857703
 744.448256
 859.225056
 1040.996262
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 10
! track = 9
! mbid = c88633ff-3a0e-4e2f-b767-ff6e5afad254
! region = Egypt
! tonic_ref = lowest_peak
