! CD10_11_Egypt.scl
!
Fin de la messe - Mîkhâ'îl Jirjis al-Batânûnî (unknown maqam, Egypt)
 5
!
 196.601293
 504.485119
 716.962266
 952.983261
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 10
! track = 11
! mbid = c99c0a4d-f598-4ff5-adb0-a44f1a15c8de
! region = Egypt
! tonic_ref = lowest_peak
