! CD10_04_Egypt.scl
!
Début de la messe : o Namo Tâyo Namo - Mîkhâ'îl Jirjis al-Batânûnî (unknown maqam, Egypt)
 5
!
 297.657754
 608.680331
 820.298265
 1102.351893
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 10
! track = 4
! mbid = 0b882da7-e468-49da-bbcb-d34c4c8f0c94
! region = Egypt
! tonic_ref = lowest_peak
