! CD10_12_Egypt.scl
!
Et av inhié Askhâ'î / Tok Tatigon / Hen e'i Frân - Mîkhâ'îl Jirjis al-Batânûnî (unknown maqam, Egypt)
 5
!
 216.849072
 489.316965
 698.174871
 867.539976
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 10
! track = 12
! mbid = 0719212f-8cde-4037-9e53-92db93c1af63
! region = Egypt
! tonic_ref = lowest_peak
