! CD10_13_Egypt.scl
!
Psaume de la tristesse / Ariba Mavi - Mîkhâ'îl Jirjis al-Batânûnî (unknown maqam, Egypt)
 6
!
 117.367367
 259.128908
 513.156812
 854.661784
 984.509375
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 10
! track = 13
! mbid = c10abe79-af6c-46f9-9a33-9083e1a645db
! region = Egypt
! tonic_ref = lowest_peak
