! CD10_03_Egypt.scl
!
Je ef Ez Maro'ot / Je peniot / Tihirini - Mîkhâ'îl Jirjis al-Batânûnî (unknown maqam, Egypt)
 4
!
 118.509915
 320.030062
 1044.272866
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 10
! track = 3
! mbid = ac7648dd-ef0b-4998-910e-cff8d971b030
! region = Egypt
! tonic_ref = lowest_peak
