! CD10_08_Egypt.scl
!
Eprushte - Mîkhâ'îl Jirjis al-Batânûnî (unknown maqam, Egypt)
 5
!
 65.735549
 596.982107
 745.566833
 904.467575
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 10
! track = 8
! mbid = e921acb8-9d1a-404a-b537-7c80958bea82
! region = Egypt
! tonic_ref = lowest_peak
