! CD11_11_Iraq.scl
!
Suite - Ensemble de Muhammad Al-Qubbbânjî (ibrahimi, Iraq)
 6
!
 172.795323
 289.578996
 491.016852
 712.088548
 988.321609
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 11
! track = 11
! mbid = aebd18ba-1edf-4f86-9d80-d9002da1cce5
! maqam = ibrahimi
! region = Iraq
! tonic_ref = lowest_peak
