! CD11_07_Iraq.scl
!
Suite - Ensemble de Muhammad Al-Qubbbânjî (ibrahimi, Iraq)
 6
!
 165.835548
 301.615899
 492.294324
 728.420935
 991.62029
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 11
! track = 7
! mbid = 6f88af35-4680-4ce4-8532-453ae1379fe6
! maqam = ibrahimi
! region = Iraq
! tonic_ref = lowest_peak
