! CD11_18_Iraq.scl
!
Suite - Ensemble de Muhammad Al-Qubbbânjî (mansuri, Iraq)
 6
!
 144.791804
 331.491828
 555.504627
 830.431357
 1038.689682
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 11
! track = 18
! mbid = 53cfc086-65a1-486a-8cf0-d7d4d82c899d
! maqam = mansuri
! region = Iraq
! tonic_ref = lowest_peak
