! CD11_17_Iraq.scl
!
Suite - Ensemble de Muhammad Al-Qubbbânjî (mansuri, Iraq)
 6
!
 147.9656
 339.608373
 559.520399
 828.767333
 1043.489335
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 11
! track = 17
! mbid = df1b4816-ac2d-45d8-926c-43708e4dfd14
! maqam = mansuri
! region = Iraq
! tonic_ref = lowest_peak
