! CD11_03_rast_Iraq.scl
!
Suite - Ensemble de Muhammad Al-Qubbbânjî (rast, Iraq)
 7
!
 215.860309
 375.94589
 498.025096
 695.840873
 909.967087
 993.169405
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 11
! track = 3
! mbid = 68abf28e-c906-4c72-b462-be8c2f213a66
! maqam = rast
! region = Iraq
! tonic_ref = annotated
! tonic_hz = 138.81
