! CD11_19_Iraq.scl
!
Suite - Ensemble de Muhammad Al-Qubbbânjî (mansuri, Iraq)
 6
!
 142.73686
 331.64159
 550.65815
 841.090559
 1042.975003
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 11
! track = 19
! mbid = b4282991-2ac7-4d17-bb0c-28c1e8fe6abb
! maqam = mansuri
! region = Iraq
! tonic_ref = lowest_peak
