! CD11_20_Iraq.scl
!
Suite - Ensemble de Muhammad Al-Qubbbânjî (mansuri, Iraq)
 5
!
 357.00674
 566.107234
 852.930837
 1057.066204
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 11
! track = 20
! mbid = e87d5f82-9952-436f-9952-0656e800462b
! maqam = mansuri
! region = Iraq
! tonic_ref = lowest_peak
