! CD11_09_Iraq.scl
!
Suite - Ensemble de Muhammad Al-Qubbbânjî (ibrahimi, Iraq)
 6
!
 161.515215
 298.319402
 497.524626
 702.644671
 996.873324
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 11
! track = 9
! mbid = c4f07153-743f-4ca3-8f1f-bdc4652a51d0
! maqam = ibrahimi
! region = Iraq
! tonic_ref = lowest_peak
