! CD12_20_Iraq.scl
!
(Suite) Le Luth est mon âme, ô chamelier - Ensemble de Muhammad Al-Qubbbânjî (unknown maqam, Iraq)
 6
!
 230.918587
 290.476705
 505.023197
 701.213116
 827.892725
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 12
! track = 20
! mbid = 8c42a775-df8d-4daa-acfb-5c943b389d3d
! region = Iraq
! tonic_ref = lowest_peak
