! CD12_03_Iraq.scl
!
Suite - Ensemble de Muhammad Al-Qubbbânjî (mukhalif, Iraq)
 7
!
 124.266191
 263.915273
 378.800533
 606.703173
 747.099822
 947.751859
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 12
! track = 3
! mbid = 24fee43e-ebe2-40cc-916b-8230e37fe0bc
! maqam = mukhalif
! region = Iraq
! tonic_ref = lowest_peak
