! CD12_19_Iraq.scl
!
Ami, ma tribu me bat Froid - Ensemble de Muhammad Al-Qubbbânjî (unknown maqam, Iraq)
 6
!
 213.508245
 275.3447
 484.359738
 704.95187
 824.922956
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 12
! track = 19
! mbid = fae444f6-363d-45fc-95a1-3e46e3dd6970
! region = Iraq
! tonic_ref = lowest_peak
