! CD12_13_Iraq.scl
!
Neuf rythmes de l'école de Bagdad, Duff Zinjârî - Ensemble de Muhammad Al-Qubbbânjî (unknown maqam, Iraq)
 4
!
 346.659035
 586.549745
 835.497113
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 12
! track = 13
! mbid = a1416f07-3d03-4c92-b2fd-39bae0f98a67
! region = Iraq
! tonic_ref = lowest_peak
