! CD12_22_Iraq.scl
!
(Suite) Et les larmes de mes yeux - Ensemble de Muhammad Al-Qubbbânjî (unknown maqam, Iraq)
 6
!
 145.170637
 369.280497
 593.160779
 838.286271
 1068.331359
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 12
! track = 22
! mbid = d95c37a5-97a0-43b6-9d06-23578ece62c9
! region = Iraq
! tonic_ref = lowest_peak
