! CD13_08_Iraq.scl
!
Taqsîm, 'ûd - Ensemble de Muhammad Al-Qubbbânjî (hakimi/huzam, Iraq)
 7
!
 176.852506
 370.704365
 580.218797
 722.456159
 866.607503
 1074.837259
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 13
! track = 8
! mbid = 381ec606-b068-47e0-9017-6f6fd9424bf0
! maqam = hakimi/huzam
! region = Iraq
! tonic_ref = lowest_peak
