! CD13_06_husayni_Iraq.scl
!
Suite - Ensemble de Muhammad Al-Qubbbânjî (husayni, Iraq)
 6
!
 168.627732
 288.312158
 490.403932
 693.035747
 994.138163
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 13
! track = 6
! mbid = 78999ffe-2e44-4790-b67a-7a54714ced98
! maqam = husayni
! region = Iraq
! tonic_ref = annotated
! tonic_hz = 118.97
