! CD14_16_Algeria.scl
!
Perle de rosée - L'ensemble d'Al-'Arabî Ben Sârî (rasd al-dhil, Algeria)
 6
!
 95.50774
 292.737735
 478.042093
 787.636962
 991.386653
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 14
! track = 16
! mbid = fbc13c75-913d-423e-80e9-e965baa81f91
! maqam = rasd al-dhil
! region = Algeria
! tonic_ref = lowest_peak
