! CD14_04_Algeria.scl
!
Suite - L'ensemble d'Al-'Arabî Ben Sârî (raml al-ashiyya, Algeria)
 6
!
 296.289286
 498.824194
 690.784497
 793.976373
 995.422477
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 14
! track = 4
! mbid = 2cd43098-3bcc-4083-b1e1-f619ed89103f
! maqam = raml al-ashiyya
! region = Algeria
! tonic_ref = lowest_peak
