! CD15_09_Morocco.scl
!
Que la paix soit avec mes parents - L'ensemble de 'Umar Fâ'id Al-Ju'aydî (unknown maqam, Morocco)
 6
!
 205.581649
 507.246077
 714.698943
 884.560773
 969.81415
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 15
! track = 9
! mbid = 513741ab-6741-4214-8464-36f3c8c2e03f
! region = Morocco
! tonic_ref = lowest_peak
