! CD15_10_Morocco.scl
!
Toi au regard étincelant - L'ensemble de 'Umar Fâ'id Al-Ju'aydî (unknown maqam, Morocco)
 6
!
 110.018807
 494.31794
 717.45187
 891.962461
 1001.07243
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 15
! track = 10
! mbid = 25654b5d-be35-4c37-99ba-6fe02bd55681
! region = Morocco
! tonic_ref = lowest_peak
