! CD15_15_Morocco.scl
!
Je n'ai plus de force - L'ensemble de 'Umar Fâ'id Al-Ju'aydî (unknown maqam, Morocco)
 5
!
 190.284114
 483.299571
 694.116066
 894.392317
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 15
! track = 15
! mbid = 6fd88cbd-2216-416f-934d-8f45ed021070
! region = Morocco
! tonic_ref = lowest_peak
