! CD16_02_Morocco.scl
!
Tûshiya - L'ensemble de 'Umar Fâ'id Al-Ju'aydî (ushshaq, Morocco)
 7
!
 210.854799
 400.896898
 504.070734
 703.216644
 892.701608
 1015.823877
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 16
! track = 2
! mbid = ed734639-c860-4f67-959b-aaa679e7c77e
! maqam = ushshaq
! region = Morocco
! tonic_ref = lowest_peak
