! CD16_06_Morocco.scl
!
Suite - L'ensemble de 'Umar Fâ'id Al-Ju'aydî (ushshaq, Morocco)
 6
!
 199.766463
 500.743816
 707.899319
 893.851259
 996.48765
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 16
! track = 6
! mbid = 5b81fc4a-a7ae-45d9-bc11-a0c361cd3dd2
! maqam = ushshaq
! region = Morocco
! tonic_ref = lowest_peak
