! CD16_05_Morocco.scl
!
Un jour merveilleux - L'ensemble de 'Umar Fâ'id Al-Ju'aydî (ushshaq, Morocco)
 6
!
 204.738229
 498.055417
 711.880228
 886.979798
 1005.346531
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 16
! track = 5
! mbid = 7791dd26-4a17-427b-999a-b7fdb21f30ba
! maqam = ushshaq
! region = Morocco
! tonic_ref = lowest_peak
