! CD17_14_Tunisia.scl
!
(Suite) Allâh, Allâh, Allâh - L'ensemble de Muhammad Ghânim (rast, Tunisia)
 6
!
 278.372407
 518.709327
 709.231309
 790.582866
 1003.599597
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 17
! track = 14
! mbid = d0376918-3d77-4aef-b4d6-8b6b41d6deb8
! maqam = rast
! region = Tunisia
! tonic_ref = lowest_peak
