! CD17_07_Tunisia.scl
!
Tawshiya 'Irâq - L'ensemble de Muhammad Ghânim (dhil, Tunisia)
 7
!
 169.412885
 274.492702
 449.344443
 667.22547
 805.307659
 976.292568
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 17
! track = 7
! mbid = 935b1f4b-7673-4765-9a12-bde47ee5d5c2
! maqam = dhil
! region = Tunisia
! tonic_ref = lowest_peak
