! CD17_02_Tunisia.scl
!
Msaddar - L'ensemble de Muhammad Ghânim (rasd al-dhil, Tunisia)
 7
!
 221.53694
 294.612382
 492.032
 678.656212
 806.768471
 995.442079
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 17
! track = 2
! mbid = 7650f41f-a6d2-43cd-966a-6c90ff53a28f
! maqam = rasd al-dhil
! region = Tunisia
! tonic_ref = lowest_peak
