! CD17_08_Tunisia.scl
!
Suite - L'ensemble de Muhammad Ghânim (rasd al-dhil, Tunisia)
 7
!
 191.626667
 294.652176
 480.942807
 669.396515
 799.754068
 988.327832
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 17
! track = 8
! mbid = f0e14281-db24-4277-a3f2-54fd31ea9016
! maqam = rasd al-dhil
! region = Tunisia
! tonic_ref = lowest_peak
