! CD18_15_Tunisia.scl
!
'Arûbî - L'ensemble de Muhammad Ghânim (mazmum, Tunisia)
 7
!
 124.584517
 318.858376
 503.707779
 641.730341
 825.051602
 1034.379289
 1200.0
!
! Bozkurt, B. (2025). An Open Research Dataset of the 1932 Cairo
! Congress of Arab Music. arXiv:2506.14503.
!
! [info]
! source = ORD-CC32
! doi = https://doi.org/10.5281/zenodo.15682346
! cd = 18
! track = 15
! mbid = 6b106d86-20aa-4d6b-bd35-930bf29fb36e
! maqam = mazmum
! region = Tunisia
! tonic_ref = lowest_peak
