! Angola_Chisende_10622.scl
!
Chisende 10622 (Likembe), Angola
 6
!
 128.0
 371.0
 498.0
 676.0
 808.0
 1161.0
!
! Kubik, Gerhard (1980). Likembe tunings of Kufuna Kandonga (Angola).
! African Music: Journal of the International Library of African Music,
! 6(1):70-88.
!
! [info]
! source = DaMuSc
! measured_id = M0197
! ref_id = 15
! country = Angola
! doi = https://doi.org/10.21504/amj.v6i1.1097
