! China_Flute_84.scl
!
84 (Flute), China
 12
!
 158.0
 338.0
 695.0
 896.0
 1142.0
 1235.0
 1399.0
 1564.0
 1926.0
 2118.0
 2277.0
 2458.0
!
! Yu-An, Rao; Carterette, Edward C.; Yu-Kui, Wu (1987). A comparison of
! the musical scales of the ancient Chinese bronze bell ensemble and the
! modern bamboo flute. Perception & Psychophysics, 41(6):547-562.
!
! [info]
! source = DaMuSc
! measured_id = M0142
! ref_id = 23
! country = China
! doi = https://doi.org/10.3758/BF03210489
