! China_Bells_86.scl
!
86 (Bells), China
 12
!
 124.0
 339.0
 657.0
 853.0
 1058.0
 1159.0
 1343.0
 1526.0
 1844.0
 2038.0
 2204.0
 2668.0
!
! Yu-An, Rao; Carterette, Edward C.; Yu-Kui, Wu (1987). A comparison of
! the musical scales of the ancient Chinese bronze bell ensemble and the
! modern bamboo flute. Perception & Psychophysics, 41(6):547-562.
!
! [info]
! source = DaMuSc
! measured_id = M0144
! ref_id = 23
! country = China
! doi = https://doi.org/10.3758/BF03210489
