! China_Bells_85.scl
!
85 (Bells), China
 12
!
 149.0
 339.0
 692.0
 884.0
 1099.0
 1186.0
 1334.0
 1551.0
 1853.0
 2047.0
 2195.0
 2678.0
!
! Yu-An, Rao; Carterette, Edward C.; Yu-Kui, Wu (1987). A comparison of
! the musical scales of the ancient Chinese bronze bell ensemble and the
! modern bamboo flute. Perception & Psychophysics, 41(6):547-562.
!
! [info]
! source = DaMuSc
! measured_id = M0143
! ref_id = 23
! country = China
! doi = https://doi.org/10.3758/BF03210489
