! Colombia_Marimba_04.scl
!
Marimba 4 (Marimba), Colombia
 19
!
 180.0
 340.0
 490.0
 670.0
 820.0
 980.0
 1135.0
 1290.0
 1460.0
 1630.0
 1800.0
 1990.0
 2125.0
 2290.0
 2450.0
 2630.0
 2800.0
 2965.0
 3120.0
!
! C. Minana Blasco. Afinacion de las marimbas en la costa pacifiica
! colombiana: Un ejemplo de la memoria intervalica africana en colombia.
! 1990
!
! [info]
! source = DaMuSc
! measured_id = M0287
! ref_id = 51
! country = Colombia
