! Colombia_Marimba_05.scl
!
Marimba 5 (Marimba), Colombia
 21
!
 210.0
 360.0
 520.0
 680.0
 890.0
 1030.0
 1190.0
 1360.0
 1530.0
 1700.0
 1870.0
 2030.0
 2190.0
 2350.0
 2500.0
 2660.0
 2870.0
 3030.0
 3150.0
 3300.0
 3400.0
!
! C. Minana Blasco. Afinacion de las marimbas en la costa pacifiica
! colombiana: Un ejemplo de la memoria intervalica africana en colombia.
! 1990
!
! [info]
! source = DaMuSc
! measured_id = M0288
! ref_id = 51
! country = Colombia
