! Ethiopia_AI_541_84_1939.scl
!
AI 541/84 -1939, Ethiopia
 5
!
 375.0
 554.0
 759.0
 1091.0
 1200.0 ! Octave added to measured scale
!
! Weisser, Stéphanie; Falceto, Francis (2013). Investigating qәñәt in
! Amhara secular music: an acoustic and historical study. Annales
! d'Ethiopie, 28(1):299-322.
!
! [info]
! source = DaMuSc
! measured_id = M0162
! ref_id = 40
! country = Ethiopia
! doi = https://doi.org/10.3406/ethio.2013.1539
