! Georgia_GVM201-M.scl
!
GVM201-M (Voice), Georgia
 8
!
 192.0
 358.0
 528.0
 701.0
 862.0
 1062.0
 1238.0
 1401.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0312
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
