! Georgia_GVM199-H.scl
!
GVM199-H (Voice), Georgia
 7
!
 184.0
 344.0
 502.0
 692.0
 953.0
 1031.0
 1157.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0324
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
