! Georgia_GVM198-M.scl
!
GVM198-M (Voice), Georgia
 6
!
 177.0
 349.0
 567.0
 764.0
 887.0
 1040.0
!
! Scherbaum, Frank; Mzhavanadze, Nana (2020). Svan Funeral Dirges (Zär):
! Musical Acoustical Analysis of a New Collection of Field Recordings.
! Musicologist, 4(2):138-167.
!
! [info]
! source = DaMuSc
! measured_id = M0309
! ref_id = 56
! country = Georgia
! doi = https://doi.org/10.33906/musicologist.782094
