! Greece_Second.scl
!
Second (Voice), Greece
 7
!
 139.0
 361.0
 493.0
 710.0
 854.0
 1017.0
 1200.0
!
! Panteli, Maria; Purwins, Hendrik (2013). A Quantitative Comparison of
! Chrysanthine Theory and Performance Practice of Scale Tuning, Steps,
! and Prominence of the Octoechos in Byzantine Chant. Journal of New
! Music Research, 42(3):205-221.
!
! [info]
! source = DaMuSc
! measured_id = M0429
! ref_id = 60
! country = Greece
! doi = https://doi.org/10.1080/09298215.2013.827215
