! Guinea_Malinke_01.scl
!
Guinea Malinke 1 (Xylophone), Guinea
 17
!
 174.0
 356.0
 533.0
 692.0
 866.0
 1034.0
 1203.0
 1366.0
 1543.0
 1705.0
 1888.0
 2063.0
 2226.0
 2396.0
 2576.0
 2738.0
 2931.0
!
! Rouget, Gilbert; Schwarz, J. (1969). Sur les xylophones
! equiheptaphoniques des Malinke. Revue de musicologie, 55(1):47.
!
! [info]
! source = DaMuSc
! measured_id = M0131
! ref_id = 8
! country = Guinea
! doi = https://doi.org/10.2307/927751
