! Guinea_Malinke_02.scl
!
Guinea Malinke 2 (Xylophone), Guinea
 17
!
 178.0
 346.0
 519.0
 684.0
 859.0
 1028.0
 1201.0
 1372.0
 1544.0
 1714.0
 1872.0
 2048.0
 2232.0
 2402.0
 2578.0
 2748.0
 2924.0
!
! Rouget, Gilbert; Schwarz, J. (1969). Sur les xylophones
! equiheptaphoniques des Malinke. Revue de musicologie, 55(1):47.
!
! [info]
! source = DaMuSc
! measured_id = M0132
! ref_id = 8
! country = Guinea
! doi = https://doi.org/10.2307/927751
