! Indonesia_Gam_GPH_Tejakusuma_Yogya.scl
!
Gam. GPH Tejakusuma Yogya (Saron Demung or Gender Barung), Indonesia
 7
!
 117.0
 258.0
 541.0
 673.0
 761.0
 925.0
 1194.0
!
! W. Surjodiningrat, A. Susanto, and P. J. Sudarjana. Tone Measurements
! of Outstanding Javanese Gamelans in Jogjakarta and Surakarta. Gadjah
! Mada University Press, 1972
!
! [info]
! source = DaMuSc
! measured_id = M0352
! ref_id = 12
! country = Indonesia
