! Indonesia_Gender_Wayang_10.scl
!
10 (Gender Wayang), Indonesia
 9
!
 172.0
 451.0
 695.0
 951.0
 1190.0
 1405.0
 1657.0
 1899.0
 2161.0
!
! Schneider, Albrecht (2001). Sound, Pitch, and Scale: From "Tone
! Measurements" to Sonological Analysis in Ethnomusicology.
! Ethnomusicology, 45(3):489.
!
! [info]
! source = DaMuSc
! measured_id = M0069
! ref_id = 27
! country = Indonesia
! doi = https://doi.org/10.2307/852868
