! Indonesia_Gender_Wayang_11.scl
!
11 (Gender Wayang), Indonesia
 9
!
 197.0
 420.0
 686.0
 939.0
 1185.0
 1414.0
 1659.0
 1904.0
 2168.0
!
! Schneider, Albrecht (2001). Sound, Pitch, and Scale: From "Tone
! Measurements" to Sonological Analysis in Ethnomusicology.
! Ethnomusicology, 45(3):489.
!
! [info]
! source = DaMuSc
! measured_id = M0070
! ref_id = 27
! country = Indonesia
! doi = https://doi.org/10.2307/852868
