! Indonesia_Konservatori_Karawitan_Gamelan_II_a.scl
!
Konservatori Karawitan Gamelan II (Saron Demung or Gender Barung), Indonesia
 7
!
 112.0
 248.0
 518.0
 639.0
 725.0
 957.0
 1191.0
!
! W. Surjodiningrat, A. Susanto, and P. J. Sudarjana. Tone Measurements
! of Outstanding Javanese Gamelans in Jogjakarta and Surakarta. Gadjah
! Mada University Press, 1972
!
! [info]
! source = DaMuSc
! measured_id = M0345
! ref_id = 12
! country = Indonesia
