! Indonesia_Saron_Barung_13.scl
!
13 (Saron Barung), Indonesia
 5
!
 230.0
 481.0
 713.0
 958.0
 1224.0
!
! Carterette, Edward C.; Kendall, Roger A.; Vale, Sue Carole De (1993).
! Comparative acoustical and psychoacoustical analyses of gamelan
! instrument tones.. Journal of the Acoustical Society of Japan (E),
! 14(6):383-396.
!
! [info]
! source = DaMuSc
! measured_id = M0072
! ref_id = 26
! country = Indonesia
! doi = https://doi.org/10.1250/ast.14.383
