! Indonesia_Gamelan_Kedokngorek_Kyahi.scl
!
Gamelan Kedokngorek Kyahi (Saron Demung or Gender Barung), Indonesia
 5
!
 228.0
 449.0
 697.0
 952.0
 1197.0
!
! W. Surjodiningrat, A. Susanto, and P. J. Sudarjana. Tone Measurements
! of Outstanding Javanese Gamelans in Jogjakarta and Surakarta. Gadjah
! Mada University Press, 1972
!
! [info]
! source = DaMuSc
! measured_id = M0381
! ref_id = 12
! country = Indonesia
