! Indonesia_Konservatori_Karawitan_Gamelan_III_a.scl
!
Konservatori Karawitan Gamelan III (Saron Demung or Gender Barung), Indonesia
 7
!
 119.0
 224.0
 492.0
 685.0
 827.0
 951.0
 1207.0
!
! W. Surjodiningrat, A. Susanto, and P. J. Sudarjana. Tone Measurements
! of Outstanding Javanese Gamelans in Jogjakarta and Surakarta. Gadjah
! Mada University Press, 1972
!
! [info]
! source = DaMuSc
! measured_id = M0359
! ref_id = 12
! country = Indonesia
