! Indonesia_Gam_GPH_Tedjakusuma.scl
!
Gam. GPH Tedjakusuma (Saron Demung or Gender Barung), Indonesia
 5
!
 236.0
 463.0
 723.0
 956.0
 1225.0
!
! W. Surjodiningrat, A. Susanto, and P. J. Sudarjana. Tone Measurements
! of Outstanding Javanese Gamelans in Jogjakarta and Surakarta. Gadjah
! Mada University Press, 1972
!
! [info]
! source = DaMuSc
! measured_id = M0373
! ref_id = 12
! country = Indonesia
