! Indonesia_Konservatori_Karawitan_Gamelan_I_a.scl
!
Konservatori Karawitan Gamelan I (Saron Demung or Gender Barung), Indonesia
 7
!
 120.0
 267.0
 540.0
 668.0
 783.0
 977.0
 1217.0
!
! W. Surjodiningrat, A. Susanto, and P. J. Sudarjana. Tone Measurements
! of Outstanding Javanese Gamelans in Jogjakarta and Surakarta. Gadjah
! Mada University Press, 1972
!
! [info]
! source = DaMuSc
! measured_id = M0342
! ref_id = 12
! country = Indonesia
