! Malawi_Asena_23.scl
!
Asena 23 (Valimba), Malawi
 16
!
 163.0
 352.0
 540.0
 694.0
 879.0
 1020.0
 1224.0
 1368.0
 1532.0
 1686.0
 1877.0
 2028.0
 2220.0
 2388.0
 2495.0
 2628.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0116
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
