! Malawi_Asena_29.scl
!
Asena 29 (Malimba), Malawi
 16
!
 208.0
 349.0
 534.0
 664.0
 898.0
 1035.0
 1181.0
 1349.0
 1571.0
 1741.0
 1914.0
 2066.0
 2205.0
 2354.0
 2475.0
 2603.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0122
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
