! Malawi_Asena_26.scl
!
Asena 26 (Valimba), Malawi
 15
!
 245.0
 418.0
 557.0
 804.0
 947.0
 1147.0
 1327.0
 1467.0
 1618.0
 1885.0
 2021.0
 2116.0
 2274.0
 2398.0
 2495.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0119
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
