! Malawi_Asena_08.scl
!
Asena 8 (Bangwe), Malawi
 8
!
 173.0
 390.0
 547.0
 707.0
 875.0
 1081.0
 1249.0
 1402.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0101
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
