! Malawi_Asena_09.scl
!
Asena 9 (Bangwe), Malawi
 7
!
 132.0
 356.0
 540.0
 708.0
 902.0
 1057.0
 1217.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0102
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
