! Malawi_Asena_14.scl
!
Asena 14 (Valimba), Malawi
 13
!
 98.0
 243.0
 362.0
 576.0
 793.0
 940.0
 1117.0
 1316.0
 1478.0
 1657.0
 1861.0
 2043.0
 2163.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0107
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
