! Malawi_Asena_19.scl
!
Asena 19 (Valimba), Malawi
 16
!
 193.0
 366.0
 542.0
 702.0
 895.0
 1068.0
 1250.0
 1438.0
 1587.0
 1761.0
 1919.0
 2095.0
 2322.0
 2450.0
 2615.0
 2827.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0112
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
