! Malawi_Asena_07.scl
!
Asena 7 (Bangwe), Malawi
 8
!
 136.0
 324.0
 510.0
 648.0
 833.0
 1027.0
 1202.0
 1382.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0100
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
