! Malawi_Asena_05.scl
!
Asena 5 (Bangwe), Malawi
 11
!
 65.0
 302.0
 477.0
 636.0
 809.0
 966.0
 1135.0
 1308.0
 1521.0
 1711.0
 1867.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0098
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
