! Malawi_Asena_31.scl
!
Asena 31 (Malimba), Malawi
 16
!
 179.0
 537.0
 691.0
 852.0
 1000.0
 1216.0
 1379.0
 1580.0
 1725.0
 1902.0
 2072.0
 2243.0
 2400.0
 2579.0
 2767.0
 2937.0
!
! Van Zanten, Wim (1980). The equidistant heptatonic scale of the Asena
! in Malawi. African Music: Journal of the International Library of
! African Music, 6(1):107-125.
!
! [info]
! source = DaMuSc
! measured_id = M0124
! ref_id = 16
! country = Malawi
! doi = https://doi.org/10.21504/amj.V6i1.1099
