! Tanzania_Ilimba_127.scl
!
127 (Ilimba), Tanzania
 16
!
 689.0
 934.0
 1191.0
 1559.0
 1888.0
 2134.0
 2387.0
 2593.0
 2774.0
 3034.0
 3117.0
 3370.0
 3583.0
 3814.0
 3906.0
 4624.0
!
! G. Kubik. A structural examination of homophonic multi-part singing in
! east and central africa. Anuario Musical, 39:27, 1984
!
! [info]
! source = DaMuSc
! measured_id = M0189
! ref_id = 20
! country = Tanzania
