! Thailand_Morton_04.scl
!
Morton 4 (Khong Wong Lek), Thailand
 14
!
 163.0
 345.0
 521.0
 692.0
 854.0
 1035.0
 1197.0
 1382.0
 1555.0
 1743.0
 1920.0
 2078.0
 2267.0
 2423.0
!
! D. Morton and C. Duriyanga. The Traditional Music of Thailand, volume
! 8. Univ of California Press, 1976
!
! [info]
! source = DaMuSc
! measured_id = M0061
! ref_id = 13
! country = Thailand
! doi = https://doi.org/10.1525/9780520321335
