! Thailand_Morton_01.scl
!
Morton 1 (Ranat Thum), Thailand
 13
!
 191.0
 352.0
 555.0
 652.0
 1024.0
 1190.0
 1546.0
 1710.0
 1879.0
 2047.0
 2214.0
 2564.0
 2727.0
!
! D. Morton and C. Duriyanga. The Traditional Music of Thailand, volume
! 8. Univ of California Press, 1976
!
! [info]
! source = DaMuSc
! measured_id = M0058
! ref_id = 13
! country = Thailand
! doi = https://doi.org/10.1525/9780520321335
