! Thailand_Morton_03.scl
!
Morton 3 (Khong Wong Yai), Thailand
 15
!
 151.0
 321.0
 504.0
 663.0
 820.0
 980.0
 1154.0
 1335.0
 1496.0
 1678.0
 1848.0
 2020.0
 2182.0
 2360.0
 2523.0
!
! D. Morton and C. Duriyanga. The Traditional Music of Thailand, volume
! 8. Univ of California Press, 1976
!
! [info]
! source = DaMuSc
! measured_id = M0060
! ref_id = 13
! country = Thailand
! doi = https://doi.org/10.1525/9780520321335
