! Zimbabwe_Matepe_02.scl
!
Matepe 2 (Mbira), Zimbabwe
 12
!
 154.0
 369.0
 507.0
 689.0
 854.0
 1040.0
 1208.0
 1390.0
 1568.0
 1706.0
 1888.0
 2073.0
!
! Tracey, Andrew (1970). The Matepe mbira music of Rhodesia. African
! Music: Journal of the African Music Society, 4(4):37-61.
!
! [info]
! source = DaMuSc
! measured_id = M0128
! ref_id = 9
! country = Zimbabwe
! doi = https://doi.org/10.21504/amj.v4i4.1681
